Dev/b.karyshev/ADEF-BBS-027 implement logger
cpp-park-vk-education/2023_1_Japanese_gardens_and_landscapes pull request #10
Opened 2023-05-17 10:08 UTC by BorisKaryshev

Ссылка на таск: https://flat-bottle-4d0.notion.site/19efc6d10b714c5ca8b748a2bbded1c0

Необходимо реализовать логгер, с помощью которого можно было бы удобно выводить какую-либо информацию

2023-05-17 17:14 UTC, GoshaSerbin reviewed
Все отлично на мой взгляд

2023-05-17 17:14 UTC, GoshaSerbin commented on libs/AnimeDefendersEngine/include/Logger/Logger.hpp
> +            void setLogLevel(LogLevel) noexcept;
Может быть auto ... -> void ?

2023-05-17 17:14 UTC, GoshaSerbin commented on libs/AnimeDefendersEngine/include/Logger/Logger.hpp
>          extern BasicLogger deafult_log;
Может быть defaultLog? Как минимум deFAult

2023-05-17 17:23 UTC, GoshaSerbin requested changes
Все здорово

2023-05-18 19:39 UTC, Arugaf requested changes

2023-05-18 19:39 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/Logger/Logger.hpp
> +            explicit BasicLogger(std::unique_ptr<std::ostream>&& stream) : m_stream{std::move(stream)} {}
Не надо писать реализацию методов в теле класса, если есть `.cpp` файл.

2023-05-18 19:39 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/Logger/Logger.hpp
> +        }
Нужно ли это в хедере здесь? Может быть в анонимный неймспейс в .`cpp` файле?

2023-05-18 19:39 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/Logger/Logger.hpp
> +            auto printWarning(const std::string& message) -> BasicLogger&;
`const` `[[nodiscard]]`

2023-05-18 19:39 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/Logger/Logger.cpp
> +using AnimeDefendersEngine::Logger::BasicLogger;
Плохо.

2023-05-18 19:39 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/Logger/Logger.cpp
> +        (*m_stream) << "Message [" << CurrentTime{} << "] " << message << '\n';
Почему в скобках часть слева?

2023-05-18 19:39 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/Logger/Logger.cpp
> +    auto noColor = "\033[0m";
Правую часть вынести как `constexpr` константы в анонимном неймспейсе.

2023-05-20 17:14 UTC, Arugaf requested changes

2023-05-20 17:14 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/Logger/Logger.hpp
> +            auto printWarning(const std::string& message) const -> const BasicLogger&;
`[[nodiscard]]`

2023-05-20 17:14 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/Logger/Logger.cpp
> +using AnimeDefendersEngine::Logger::BasicLogger;
Все еще очень плохо, я не буду это пропускать.

2023-05-23 06:25 UTC, BorisKaryshev commented on libs/AnimeDefendersEngine/src/Logger/Logger.cpp
> +using AnimeDefendersEngine::Logger::BasicLogger;
Как я понял, речь про использование сишной структуры
На текущий момент в GCC chrono до конца не реализовано и вывод в поток отсутствует

Так что если не использовать time_t, то мне придётся либо самому писать преобразование к дате, либо подключать либу, а ни того, ни другого делать как-то не хочется

2023-05-23 07:51 UTC, GoshaSerbin approved these changes, later dismissed

2023-05-23 13:46 UTC, Arugaf requested changes

2023-05-23 13:46 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/Logger/Logger.cpp
> +using AnimeDefendersEngine::Logger::BasicLogger;
Речь про то, чтобы обернуть реализации неймспейсом, вместо того, чтобы использовать `using namespace`.

2023-05-23 13:46 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/Logger/Logger.cpp
> +        auto milliseconds = std::chrono::duration_cast<std::chrono::milliseconds>(timePoint.time_since_epoch()) % 1000;
`const auto`

2023-05-23 13:46 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/Logger/Logger.cpp
> +               << milliseconds.count() << " " << now->tm_mday << '.' << (now->tm_mon + 1) << '.' << (now->tm_year + 1900);
`1900` в отдельную константу в анонимном неймспейсе.

2023-05-23 14:39 UTC, GoshaSerbin approved these changes

2023-05-23 14:42 UTC, Arugaf approved these changes

2023-05-23 15:10 UTC, merged