[ADEF-BBS-045] Math: Vector2: Implemented Vector2 operators and functions
cpp-park-vk-education/2023_1_Japanese_gardens_and_landscapes pull request #11
Opened 2023-05-17 19:32 UTC by MiraiRatchet

2023-05-18 15:55 UTC, GoshaSerbin requested changes
В описании пул реквеста еще желательно ссылку на соответствующий таск оставить

2023-05-18 15:55 UTC, GoshaSerbin commented on libs/AnimeDefendersEngine/include/Math/Vector2.hpp
> +#include "math.h"
Вроде как math.h это сишная библиотека, а в плюсах есть <cmath>, в которой пространство имен std, и которую лучше использовать

2023-05-18 19:15 UTC, GoshaSerbin approved these changes, later dismissed

2023-05-18 19:47 UTC, Arugaf requested changes
Очень не хватает какого-нибудь constraint на уровне концептов или с использованием `type_traits` библиотеки.

2023-05-18 19:47 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/Math/Vector2.hpp
> +            auto print() -> void { std::cout << "(" << x << ", " << y << ")" << std::endl; }
Привязка к стандартному потоку вывода - плохо.

`std::endl` без понимания его работы - тоже плохо.

2023-05-18 19:47 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/Math/Vector2.hpp
> +            auto norm() -> T { return sqrt(this * this); }
Посмотреть нельзя ли оптимизировать.

2023-05-18 19:47 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/Math/Vector2.hpp
>          struct Vector2 {
Простенькую маленькую документацию про сам класс было бы неплохо набросать.

2023-05-18 19:47 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/Math/Vector2.hpp
> +        template <typename T>
Разделение потерялось.

2023-05-21 13:46 UTC, MiraiRatchet commented on libs/AnimeDefendersEngine/include/Math/Vector2.hpp
> +            auto norm() -> T { return sqrt(this * this); }
Не очень поняла, как в данном случае можно оптимизировать норму. Т.к. нам нужна именно норма, а не норма в квадрате, все равно потом придется вручную ее под квадрат помещать.

2023-05-22 18:23 UTC, Arugaf requested changes

2023-05-22 18:23 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/Math/Vector2.hpp
> +            return Vector2<T>(vec1.x + vec2.x, vec1.y + vec2.y);
Не нужно указывать возвращаемый тип в `return` statement. Можно просто использовать `{}`.

2023-05-22 18:23 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/Math/Vector2.hpp
> +        auto operator*(const double& c1, const Vector2<T>& vec1) -> Vector2<T> {
Почему привязка к double? Имеет ли тогда смысл шаблонизация вектора?

2023-05-22 20:14 UTC, MiraiRatchet commented on libs/AnimeDefendersEngine/include/Math/Vector2.hpp
> +        auto operator*(const double& c1, const Vector2<T>& vec1) -> Vector2<T> {
Убрала шаблонизацию

2023-05-23 09:16 UTC, GoshaSerbin submitted a review, later dismissed
LGTM!

2023-05-23 13:49 UTC, Arugaf requested changes

2023-05-23 13:49 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/Math/Vector2f.cpp
> +    y = y * (threeHalves - (number * 0.5f * y * y));
Привести к "плюсовому" виду.

2023-05-23 13:49 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/Math/Vector2f.cpp
> +    i = 0x5f3759df - (i >> 1);
Константу слева вынести в анонимный неймспейс.

2023-05-23 13:49 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/Math/Vector2f.cpp
> +}
Весь этот метод не особо имеет отношение к `Vector2f`. Вынести как отдельную функцию в анонимный неймспейс.

2023-05-23 13:49 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/Math/Vector2f.cpp
> +}
Обернуть все методы целиком в
```cpp
namespace AnimeDefendersEngine {
} // namespace AnimeDefendersEngine
```

2023-05-23 13:49 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/Math/Vector2f.cpp
> +}
Потерялась пустая строка.

2023-05-23 22:09 UTC, Arugaf requested changes

2023-05-23 22:09 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/Math/Vector2f.hpp
> +        float inverseSquareRoot(const float n);
Не нужно здесь? Будет объявлена и определена чисто в анонимном неймспейсе.

2023-05-23 22:09 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/Math/Vector2f.hpp
> +            explicit Vector2f(float val1 = float{}, float val2 = float{}) : x(val1), y(val2) {}
В дефолтных параметрах будет нагляднее указать `0.f`.

2023-05-23 22:09 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/Math/Vector2f.hpp
> +        float inverseSquareRoot(const float n);
Передается по значению, `const` не нужен.

2023-05-23 22:09 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/Math/Vector2f.hpp
> +        auto operator*(const Vector2f& vec1, const float& c1) -> Vector2f;
Убрать объявления в тело класса.

2023-05-23 22:09 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/Math/Vector2f.hpp
> +        auto operator*(const Vector2f& vec1, const float& c1) -> Vector2f;
Vector2f - очень маленькая структурка. В данном случае лучше передавать ее по значению.

2023-05-23 22:09 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/Math/Vector2f.cpp
> +        float xhalf = 0.5f * number;
nit: можно `auto`.

2023-05-24 10:02 UTC, MiraiRatchet commented on libs/AnimeDefendersEngine/include/Math/Vector2f.hpp
> +        auto operator*(const Vector2f& vec1, const float& c1) -> Vector2f;
Так ведь смысл как раз в том, что это именно функции, а не методы класса?..

2023-05-24 18:25 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/Math/Vector2f.hpp
> +        auto operator*(const Vector2f& vec1, const float& c1) -> Vector2f;
Большинство имеющихся операторов можно объявить как методы класса с одним (правым) аргументом. Останется только функция, где первый (левый) аргумент будет не объект этого класса. В данном случае умножение числа на вектор. Эту функцию действительно нужно объявить в хедере отдельно. В классе ее можно указать как friend функцию, чтобы показать возможность такого действия.

2023-05-24 18:25 UTC, Arugaf requested changes

2023-05-24 18:25 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/Math/Vector2f.cpp
> +    auto Math::operator*(const float& c1, Vector2f vec1) -> Vector2f {
`float` лучше передавать по значению, т.к. он слишком маленький по размеру.

2023-05-25 02:51 UTC, Arugaf requested changes

2023-05-25 02:51 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/Math/Vector2f.hpp
> +        auto operator*(Vector2f vec1,float c1) -> Vector2f;
Это все равно вне тела класса, получается...

2023-05-25 09:58 UTC, Arugaf approved these changes, later dismissed
LGTM

2023-05-25 10:00 UTC, GoshaSerbin submitted a review, later dismissed
LGTM

2023-05-25 10:12 UTC, GoshaSerbin approved these changes, later dismissed

2023-05-25 10:34 UTC, DPeshkoff requested changes, later dismissed

2023-05-25 10:34 UTC, DPeshkoff commented on libs/AnimeDefendersEngine/src/Math/Vector2f.cpp
> +        std::memcpy(&number, &i, sizeof(number));
Мне кажется, здесь лучше заюзать `reinterpret_cast`. Простая конверсия вызовет UB, круто, что вы ее избежали, но сейчас два лишних memcpy. Кажется, что можно оптимальнее

2023-05-25 10:34 UTC, DPeshkoff commented on libs/AnimeDefendersEngine/src/Math/Vector2f.cpp
> +    constexpr int invSquareRootConstant = 0x5f3759df;
Может быть проблема с магической константой. В идеале вектор должен поддерживать как `float`, так и `double`. При `double` на x64 машине нужно будет немного другое число (но там и выигрыша особо не будет)

В идеале нужна проверка по системным параметрам. 

По константе для `float` - по предельной относительной погрешности лучше использовать `0x5F375A86`

2023-05-28 16:27 UTC, GoshaSerbin approved these changes, later dismissed
LGTM

2023-05-28 16:50 UTC, GoshaSerbin approved these changes

2023-05-28 18:35 UTC, Arugaf approved these changes
Сойдет.

2023-05-28 19:08 UTC, merged