[ADEF-BBS-027] Core: Game Loop: GameLoop impelemantation
cpp-park-vk-education/2023_1_Japanese_gardens_and_landscapes pull request #12
Opened 2023-05-18 14:32 UTC by GoshaSerbin

[Ссылка на таск](https://www.notion.so/GameLoop-35b7c9c486ad4f4db8866de59c447311?pvs=4)

Запускает системы и координирует ивенты
Требуется проработка Events

2023-05-18 14:56 UTC, BorisKaryshev requested changes
Вполне неплохо, но очень не хватает `EventManager`

2023-05-18 14:56 UTC, BorisKaryshev commented on libs/AnimeDefendersEngine/include/AnimeFramework/GameLoop.hpp
> +                 ComponentManager* componentManager, float fixedDeltaTime, float maxDeltaTime);
`ComponentManager` - часть сцены, так что передавать нет смысла

2023-05-18 14:56 UTC, BorisKaryshev commented on libs/AnimeDefendersEngine/include/AnimeFramework/GameLoop.hpp
> +        float m_fixedDeltaTime{1.0f / 60.0f};
Магические числа
Стоит вынести как именованные константы

2023-05-18 14:56 UTC, BorisKaryshev commented on libs/AnimeDefendersEngine/src/AnimeFramework/GameLoop.cpp
> +            m_systemManager->updateSystems(*m_componentManager, m_fixedDeltaTime);
Он должен передавать в `SystemManager` ссылку на `SceneManager`

2023-05-18 14:56 UTC, BorisKaryshev commented on libs/AnimeDefendersEngine/include/AnimeFramework/GameLoop.hpp
> +        SceneManager* m_sceneManager;
Хранить как ссылку?
Или `std::shared_ptr`?

2023-05-18 14:56 UTC, BorisKaryshev commented on libs/AnimeDefendersEngine/src/AnimeFramework/GameLoop.cpp
> +}
Очень не хватает `EventManager`
На текущий момент цикл в `run()` бесконечный

Может проверять на ивент типа `EndGame`? @MiraiRatchet, у нас же есть такой?

2023-05-18 14:56 UTC, BorisKaryshev commented on libs/AnimeDefendersEngine/src/AnimeFramework/GameLoop.cpp
> +        float getCurrentTimeInMilliseconds() {
Trailing return type

2023-05-18 14:56 UTC, BorisKaryshev commented on libs/AnimeDefendersEngine/src/AnimeFramework/GameLoop.cpp
> +        std::chrono::time_point<std::chrono::high_resolution_clock> m_startTime;
Честно говоря, не понял зачем эта переменная нужна вообще

2023-05-18 16:06 UTC, GoshaSerbin commented on libs/AnimeDefendersEngine/src/AnimeFramework/GameLoop.cpp
> +        std::chrono::time_point<std::chrono::high_resolution_clock> m_startTime;
Я подумал что может быть полезно ресетить таймер, чтобы он показывал время, прошедшее с конкретного момента, а не системное. Соответственно нужна переменная чтобы хранить точку старта

2023-05-23 13:47 UTC, BorisKaryshev requested changes
Всё круто, но есть серьёзная ошибка с использованием именованных констант (связывание `constexpr` переменных)

2023-05-23 13:47 UTC, BorisKaryshev commented on libs/AnimeDefendersEngine/include/AnimeFramework/Event.hpp
> +        Event(std::string name, EventType type, std::string add = "") : m_name(name), m_eventType(type), m_additional(add) {}
Строчки передаются по значению, хотя можно по ссылке

2023-05-23 13:47 UTC, BorisKaryshev commented on libs/AnimeDefendersEngine/include/AnimeFramework/Event.hpp
> +        auto getName() -> std::string { return m_name; }
`[[nodiscard]]`?
Пометить методы как `const`,
Ещё можно возвращать `const std::string&`

2023-05-23 13:47 UTC, BorisKaryshev commented on libs/AnimeDefendersEngine/include/AnimeFramework/GameLoop.hpp
> +constexpr float defaultMinUpdateFrequency = 25.f;
Насколько я знаю, у `constexpr` переменных внешнее связывание, так что может возникнуть проблема множественного определения при линковке
Стоит поместить в анонимный неймспейс, или пометить `inline`

2023-05-23 13:47 UTC, BorisKaryshev commented on libs/AnimeDefendersEngine/include/AnimeFramework/InputManager.hpp
> +            int y;
Не хватает значения по умолчанию

2023-05-23 13:47 UTC, BorisKaryshev commented on libs/AnimeDefendersEngine/include/Graphics/IWindow.hpp
> +            virtual auto setWindowKeyboardListener(void (*)(unsigned char, int, int)) const -> void = 0;
Указатели на функции тяжело читать
Было бы круто ввести синонимы, например
`using Name = void(*)(int, int);`

2023-05-23 13:47 UTC, BorisKaryshev commented on libs/AnimeDefendersEngine/src/AnimeFramework/InputManager.cpp
> +        auto event = std::make_unique<Event>("Key" + key, EventType::KeyPressed);
Может стоит в ивенты добавить какой-то стандартный разделитель или стандартизировать ширину ключа типа, чтобы можно было легко извлечь тип ивента?

2023-05-24 09:43 UTC, BorisKaryshev requested changes
Вполне неплохо, но есть что поправить

2023-05-24 09:43 UTC, BorisKaryshev commented on libs/AnimeDefendersEngine/include/Systems/SystemManager.hpp
> +        virtual void updateSystems(SceneManager&, float) = 0;
Не хватает названий переменных - не понятно что они собой представляют

2023-05-24 09:43 UTC, BorisKaryshev commented on libs/AnimeDefendersEngine/src/AnimeFramework/GameLoop.cpp
> +                   1.f / defaultMinUpdateFrequency) {}
Может использовать значения для аргументов по умолчанию?

2023-05-24 09:43 UTC, BorisKaryshev commented on libs/AnimeDefendersEngine/src/AnimeFramework/GameLoop.cpp
> +    auto GameLoop::setSystemManager(std::unique_ptr<ISystemManager> systemManager) -> void {
Можно пометить как `noexcept`

2023-05-24 09:43 UTC, BorisKaryshev commented on libs/AnimeDefendersEngine/src/AnimeFramework/GameLoop.cpp
> +    auto GameLoop::setRenderer(std::unique_ptr<Graphics::Renderer> renderer) -> void {
Тоже можно пометить как `noexcept`

2023-05-24 09:43 UTC, BorisKaryshev commented on libs/AnimeDefendersEngine/src/AnimeFramework/GameLoop.cpp
> +            auto getCurrentTimeInMilliseconds() -> float {
`const` метод?

2023-05-24 09:43 UTC, BorisKaryshev commented on run.sh
> +./build/AnimeDefenders
Этого файла тут быть не должно

2023-05-24 10:37 UTC, GoshaSerbin commented on libs/AnimeDefendersEngine/src/AnimeFramework/GameLoop.cpp
> +                   1.f / defaultMinUpdateFrequency) {}
Вроде как Сеня такой вариант одобряет больше

2023-05-24 18:36 UTC, Arugaf requested changes

2023-05-24 18:36 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/AnimeFramework/EventManager.hpp
>      };
Интерфейс в отдельный файл.

2023-05-24 18:36 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/AnimeFramework/EventManager.hpp
> +        auto hasEvent(std::string eventName) -> bool;
Точно ли `eventName` должен передаваться по значению, а не по константной ссылке?

2023-05-24 18:36 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/AnimeFramework/EventManager.hpp
> +        static auto update() -> void;
Странное наследование вышло. Чем вообще обусловлен тот факт, что методы статические?

2023-05-24 18:36 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/AnimeFramework/GameLoop.hpp
> +    }
`  // namespace Graphics`

2023-05-24 18:36 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/AnimeFramework/EventManager.hpp
> +        auto hasEvent(std::string eventName) -> bool;
Виртуальный деструктор!

2023-05-24 18:36 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/AnimeFramework/GameLoop.hpp
> +        float m_fixedDeltaTime;
Дефолтная инициализация через `{}`.

2023-05-24 18:36 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/Systems/SystemManager.hpp
> +        virtual void updateSystems(SceneManager&, float) = 0;
Непонятно что за переменные.

2023-05-24 18:36 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/Systems/SystemManager.hpp
>      };
В отдельный файл.

2023-05-24 18:36 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/Systems/SystemManager.hpp
>      };
Виртуальный деструктор!

2023-05-24 18:36 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/AnimeFramework/GameLoop.cpp
> +                       SceneManager& sceneManager, float fixedDeltaTime, float maxDeltaTime)
Если аргументы приходится переносить, то нужно каждый аргумент указывать на отдельной строчке. Иначе просто напросто неудобно читать.

2023-05-24 18:36 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/AnimeFramework/GameLoop.cpp
> +        setRenderer(std::move(renderer));
Почему бы вместо этих методов просто не инициализировать соответствующие поля в списке инициализации?

2023-05-24 18:36 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/AnimeFramework/GameLoop.cpp
> +        };
Предлагаю использовать алиасы для лучшей читаемости.

2023-05-24 18:36 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/AnimeFramework/GameLoop.cpp
> +    }  // namespace
Не нужно в середине вставлять приватные классы. Выше уже был объявлен анонимный неймспейс.

2023-05-24 18:36 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/AnimeFramework/GameLoop.cpp
> +        float accumulator{0};
Просто `= 0.f;`.

2023-05-24 18:36 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/AnimeFramework/GameLoop.cpp
> +        Timer timer;
`{}`

2023-05-24 18:36 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/AnimeFramework/GameLoop.cpp
> +            float deltaTime = newTime - timeElapsedSinceLastUpdate;
`const auto`

2023-05-24 18:36 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/AnimeFramework/GameLoop.cpp
> +                if (EventManager::hasEvent("GameEnd")) {
Вынести `GameEnd` в отдельную функцию геттер в анонимном неймспейсе и вызывать ее тут.

2023-05-24 19:08 UTC, GoshaSerbin commented on libs/AnimeDefendersEngine/src/AnimeFramework/GameLoop.cpp
> +            float deltaTime = newTime - timeElapsedSinceLastUpdate;
Вряд ли const, эти переменные меняются от итерации к итерации

2023-05-24 19:20 UTC, GoshaSerbin commented on libs/AnimeDefendersEngine/include/Systems/SystemManager.hpp
>      };
В другой ветке будет исправлено

2023-05-24 19:20 UTC, GoshaSerbin commented on libs/AnimeDefendersEngine/include/AnimeFramework/EventManager.hpp
>      };
В другой ветке будет исправлено

2023-05-24 19:25 UTC, GoshaSerbin commented on libs/AnimeDefendersEngine/src/AnimeFramework/GameLoop.cpp
> +                       SceneManager& sceneManager, float fixedDeltaTime, float maxDeltaTime)
Таск сделан

2023-05-24 20:30 UTC, BorisKaryshev submitted a review, later dismissed
LGTM

2023-05-25 02:53 UTC, Arugaf requested changes

2023-05-25 02:53 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/Systems/SystemManager.hpp
> +        ~ISystemManager(){};
`= default`

2023-05-25 02:53 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/Systems/SystemManager.hpp
>      };
В отдельный файл.

2023-05-25 06:18 UTC, Arugaf approved these changes

2023-05-25 06:18 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/AnimeFramework/GameLoop.cpp
> +        float accumulator{0};
nit

2023-05-25 08:06 UTC, MiraiRatchet approved these changes

2023-05-25 08:27 UTC, merged