[ADEF-BBS-006] Physics: Collision: impelementation of collision handler resolve
cpp-park-vk-education/2023_1_Japanese_gardens_and_landscapes pull request #14
Opened 2023-05-19 10:52 UTC by GoshaSerbin

[Ссылка на таск](https://flat-bottle-4d0.notion.site/CollisionHandler-096443ae541c456e9d32e5bc9793037b)

Реализовать разрешение коллизий класса CollisionHandler

2023-05-20 17:11 UTC, Arugaf requested changes

2023-05-20 17:11 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/Physics/Body.hpp
> +        virtual auto isTrigger() const noexcept -> bool;
`[[nodiscard]]`

2023-05-20 17:11 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/Physics/CollisionHandler.hpp
> +        [[nodiscrad]] virtual auto broadPhase(const std::vector<Body*>& bodies) const -> std::vector<Manifold> override final;
Опечатка в атрибуте.

2023-05-20 17:11 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/Physics/CollisionHandler.hpp
> +    };
В отдельный файл.

2023-05-20 17:11 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/Physics/PhysicsWorld.hpp
> +}  // namespace AnimeDefendersEngine::Physics
Пустая строчка потерялась.

2023-05-20 17:11 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/Physics/Shape.hpp
> +    };
Спрашивал в тот раз, спрошу и в этот. Зачем все же здесь числовое представление?

2023-05-20 17:11 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/Physics/Shape.hpp
> +        static constexpr int shapeCount = 2;
Аналогично: почему тут переменная определена? Кем она будет использоваться?

2023-05-20 17:11 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/Physics/Shape.hpp
> +        static constexpr int shapeCount = 2;
Публичные переменные идут под отдельным модификатором доступа.

2023-05-20 17:11 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/Physics/Shape.hpp
> +        virtual ~Shape();
`= default`

2023-05-20 17:11 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/Physics/Shape.hpp
> +        explicit Rectangle(const Math::Vector2f& size);
Принимать по значению и мувать в поле.

2023-05-20 17:11 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/Physics/CollisionHandler.cpp
>  using namespace AnimeDefendersEngine::Physics;
Не надо так делать, пожалуйста.

2023-05-20 17:11 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/Physics/CollisionHandler.cpp
> +#include "Vector2.hpp"
Смешались разные группы хедеров.

2023-05-20 17:11 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/Physics/CollisionHandler.cpp
> +        float distance = (bodyA->getPosition() - bodyB->getPosition()).norm();
`const auto`

2023-05-20 17:11 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/Physics/CollisionHandler.cpp
> +        float yExtent = rectangleA->size.y / 2;
`const auto`

2023-05-20 17:11 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/Physics/CollisionHandler.cpp
> +        auto normal = distance - closestVertexToCircleCenter;
`const auto`

2023-05-20 17:11 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/Physics/CollisionHandler.cpp
> +        AnimeDefendersEngine::Math::Vector2<float> normal = bodyB->getPosition() - bodyA->getPosition();
`const auto`

2023-05-20 17:11 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/Physics/CollisionHandler.cpp
> +    return hasCollisionTypes[static_cast<int>(bodyA->getShapeType())][static_cast<int>(bodyB->getShapeType())](bodyA, bodyB);
Плохочитаемо.

2023-05-20 17:11 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/Physics/CollisionHandler.cpp
> +        float totalRadius = circleA->radius + circleB->radius;
`const auto`

2023-05-20 17:11 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/Physics/CollisionHandler.cpp
> +        contact.normal = (1.0f / distance) * direction;
`1.f`

2023-05-20 17:11 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/Physics/CollisionHandler.cpp
> +    if (relativeVelocityProjection > 0) return;
Выпадает из общего стиля.

2023-05-20 18:32 UTC, AngelicHedgehog requested changes
В общем, кода много (относительно), выглядит мощно

2023-05-20 18:32 UTC, AngelicHedgehog commented on libs/AnimeDefendersEngine/include/Physics/Body.hpp
> +        size_t m_id;
Нужен ли здесь дефолтный конструктор?

2023-05-20 18:32 UTC, AngelicHedgehog commented on libs/AnimeDefendersEngine/include/Physics/BodyDefinition.hpp
>  #include "Vector2.hpp"
```
#include "Shape.hpp"
#include "Vector2.hpp"

#include <memory>
```

2023-05-20 18:32 UTC, AngelicHedgehog commented on libs/AnimeDefendersEngine/include/Physics/BodyDefinition.hpp
> +        size_t layers{0};
`size_t layers{0}` === `size_t layers{}`
`bool isTrigger{false}` === `bool isTrigger{}`

2023-05-20 18:32 UTC, AngelicHedgehog commented on libs/AnimeDefendersEngine/include/Physics/CollisionHandler.hpp
>  #include "Manifold.hpp"
```
#include "Body.hpp"
#include "Manifold.hpp"

#include <vector>
```

2023-05-20 18:32 UTC, AngelicHedgehog commented on libs/AnimeDefendersEngine/src/Physics/Body.cpp
> +auto Body::setType(BodyType bodyType) noexcept -> void {
`noexcept` имеет смысл только в хэдере

2023-05-20 18:38 UTC, AngelicHedgehog commented on libs/AnimeDefendersEngine/include/Physics/BodyDefinition.hpp
> +        size_t layers{0};
Вместо `size_t` следует использовать `std::size_t` (относится ко всем файлам)

2023-05-21 16:13 UTC, Arugaf requested changes

2023-05-21 16:13 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/Physics/Body.hpp
> +        [[nodiscard]] virtual auto getID() const noexcept -> std::string;
`const std::string&`

2023-05-21 16:13 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/Physics/CollisionHandler.hpp
> +        virtual auto hasCollision(Body* bodyA, Body* bodyB) const -> bool override;
`[[nodiscard]]`

2023-05-21 16:13 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/Physics/ICollisionHandler.hpp
> +        virtual ~ICollisionHandler(){};
`= default`

2023-05-21 16:13 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/Physics/ICollisionHandler.hpp
> +        virtual auto hasCollision(Body* bodyA, Body* bodyB) const -> bool = 0;
`[[nodiscard]]`

2023-05-21 16:13 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/Physics/Manifold.hpp
> +        explicit Manifold(Body* bodyA, Body* bodyB);
Можно без `explicit`.

2023-05-21 16:13 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/Physics/Manifold.hpp
> +        auto correctPositions() -> void;
Хотя бы пустой строчкой отделить от полей.

2023-05-21 16:13 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/Physics/Manifold.hpp
> +        Body* bodyB;
`nullptr`

2023-05-21 16:13 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/Physics/PhysicsWorld.hpp
> +        PhysicsWorld(std::unique_ptr<CollisionHandler>&& collisionHandler, float fixedDeltaTime, float maxDeltaTime);
Нет смысла передавать `std::unique_ptr` по rvalue ссылке.

2023-05-21 16:13 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/Physics/Shape.hpp
> +        static constexpr int shapeCount = 2;
nit: все же относительно костыльненько. Просто имейте в виду.

2023-05-21 16:13 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/Physics/Shape.hpp
> +        float radius;
Дефолтное значение.

2023-05-21 16:13 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/Physics/Body.cpp
> +    m_transform.position = m_transform.position + deltaTime * m_velocity;
Лучше явно указать приоритет через скобки.

2023-05-21 16:13 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/Physics/Body.cpp
>  using namespace AnimeDefendersEngine::Physics;
От этого точно надо избавиться.

2023-05-21 16:13 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/Physics/Body.cpp
> +    m_force = AnimeDefendersEngine::Math::Vector2f(0, 0);
Слишком verbose.

2023-05-21 16:13 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/Physics/Body.cpp
> +    m_force = AnimeDefendersEngine::Math::Vector2f(0, 0);
Дефолтный конструктор?

2023-05-21 16:13 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/Physics/BodyDefinition.cpp
>        isTrigger(other.isTrigger) {}
Почему не `default`?

2023-05-21 16:13 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/Physics/CollisionHandler.cpp
> +        auto normal = distance - closestVertexToCircleCenter;
Все еще актуально.

2023-05-21 16:13 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/Physics/CollisionHandler.cpp
> +    using hasCollisionFunctionPtr = bool (*)(Body* bodyA, Body* bodyB);
Может лучше через `std::function`?

2023-05-21 16:13 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/Physics/CollisionHandler.cpp
> +        contact.normal = normal;
```cpp
contact.normal = distance - closestVertexToCircleCenter;
```

2023-05-21 16:13 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/Physics/CollisionHandler.cpp
> +    using specifyCollisionFunctionPtr = void (*)(Manifold& contact);
`std::function`?

2023-05-21 16:13 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/Physics/CollisionHandler.cpp
> +constexpr float correctionPercent = 0.5f;
В анонимный неймспейс.

2023-05-21 16:13 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/Physics/CollisionHandler.cpp
> +    specifyCollisionTypes[static_cast<int>(contact.bodyA->getShapeType())][static_cast<int>(contact.bodyB->getShapeType())](contact);
Разбить на несколько строк, чтобы было более читаемо.

2023-05-21 16:13 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/Physics/CollisionHandler.cpp
> +    if (relativeVelocityProjection > 0) return;
Все еще выпадает из общего стиля.

Даже однострочные условия/циклы и т.п. надо оборачивать фигурными скобками и не записывать в одну строку.

2023-05-21 16:13 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/Physics/CollisionHandler.cpp
> +    Vector2f impulse = impulseMagnitude * contact.normal;
`const auto`

2023-05-21 16:13 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/Physics/Manifold.cpp
> +constexpr float tolerance = 0.05f;
В анонимный неймспейс.

2023-05-21 16:13 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/Physics/Manifold.cpp
> +        correctionPercent * std::max(penetration - tolerance, 0.0f) / (bodyA->getInverseMass() + bodyB->getInverseMass()) * normal;
`0.f`

2023-05-21 20:00 UTC, Arugaf approved these changes, later dismissed
LGTM

2023-05-21 20:00 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/Physics/BodyDefinition.hpp
> +        std::string id{};
nit: в полях класса для нетривиальных типов уже будет вызван дефолтный конструктор при отсутствии инициализатора.

2023-05-21 20:02 UTC, AngelicHedgehog submitted a review, later dismissed
ok

2023-05-22 10:29 UTC, Arugaf approved these changes

2023-05-22 13:16 UTC, AngelicHedgehog approved these changes

2023-05-22 13:18 UTC, merged