[ADEF_BBS-031] Objects: implement entity scene scene manager and entity deletion mechanics
cpp-park-vk-education/2023_1_Japanese_gardens_and_landscapes pull request #16
Opened 2023-05-20 11:06 UTC by BorisKaryshev

[Таск](https://flat-bottle-4d0.notion.site/Entity-Scene-SceneManager-f5a39a919ff04c118bd77fd826a41acb)

Требуется реализовать сущность, сцену - контейнер сущностей и менеджер сцен - контейнер сцен
Также необходимо реализовать систему удаления сущностей через их метод (при этом `id` компоненты заносится в очередь в сцену, и удаляется при вызове метода `update()` у сцены)

2023-05-20 16:36 UTC, Arugaf requested changes
Очень много ругается clang-tidy.

2023-05-20 16:36 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/AnimeFramework/Entity.hpp
> +        virtual ~Entity(){};
`= default`

2023-05-20 16:36 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/AnimeFramework/Entity.hpp
> +        auto getId() -> std::string const;
```cpp
auto getId() const -> const std::string&;
```

?

2023-05-20 16:36 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/AnimeFramework/Entity.hpp
> +        auto getId() -> std::string const;
`[[nodiscard]]`

2023-05-20 16:36 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/AnimeFramework/Scene.hpp
> +        auto addEntity(std::string id, EntityCreator<Scene> auto create) -> void { m_entities[id] = create(id, *this); }
Почему вне `.cpp` файла?

2023-05-20 16:36 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/AnimeFramework/Scene.hpp
> +        auto addEntity(std::string id, EntityCreator<Scene> auto create) -> void { m_entities[id] = create(id, *this); }
Мб ссылка на `EntityCreator<Scene>`?

2023-05-20 16:36 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/AnimeFramework/Scene.hpp
> +        auto getSceneId() const noexcept -> int;
На все геттеры точно `[[nodiscard]]`

2023-05-20 16:36 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/AnimeFramework/Scene.hpp
> +        ComponentManager m_components;
Странноватое название поля.

2023-05-20 16:36 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/AnimeFramework/SceneManager.hpp
> +        [[nodiscard]] virtual auto getActiveScene() -> Scene& = 0;
`const` на метод.

2023-05-20 16:36 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/AnimeFramework/SceneManager.hpp
>      };
Имплементацию в отдельный файл.

2023-05-20 16:36 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/AnimeFramework/Scene.cpp
> +    }
Зачем так сложно? Это же вектор.

```cpp
for (const auto& id : m_entityIdsToDestroy) {
    m_entities.erase(id);
}
m_entityIdsToDestroy.clear();
```

2023-05-20 16:36 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/AnimeFramework/SceneManager.cpp
> +    auto scenePointer = m_scenes.at(m_activeSceneId).get();
Советую не использовать названия типов (и вещи вида pointer/reference) в именах переменных. В методах ок.

2023-05-20 16:36 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/AnimeFramework/SceneManager.cpp
> +    return *scenePointer;
В целом нет смысла разделять на две строчки. Можно просто сразу вернуть правую часть.

2023-05-20 16:36 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/AnimeFramework/SceneManager.cpp
> +auto SceneManager::addScene(std::unique_ptr<Scene>&& scene) -> void {
Убрать rvalue ссылку.

2023-05-23 06:43 UTC, BorisKaryshev commented on libs/AnimeDefendersEngine/include/AnimeFramework/Scene.hpp
> +        auto addEntity(std::string id, EntityCreator<Scene> auto create) -> void { m_entities[id] = create(id, *this); }
Потому что это шаблон

2023-05-23 06:55 UTC, BorisKaryshev commented on libs/AnimeDefendersEngine/include/AnimeFramework/SceneManager.hpp
> +        [[nodiscard]] virtual auto getActiveScene() -> Scene& = 0;
Получив через это геттер ссылку на `Scene`, её можно модифицировать, т.е. можно модифицировать и `SceneManager`, частью которого является `Scene`

Точно метод должен быть `const`?

2023-05-23 13:53 UTC, Arugaf submitted a review, later dismissed
LGTM

2023-05-23 14:07 UTC, GoshaSerbin submitted a review, later dismissed
LGTM!

2023-05-23 14:25 UTC, merged