Dev/b.karyshev/adef bbs 002 implement class for easy tables reading from stream
cpp-park-vk-education/2023_1_Japanese_gardens_and_landscapes pull request #17
Opened 2023-05-20 11:18 UTC by BorisKaryshev

[Таск](https://flat-bottle-4d0.notion.site/cf8573603c214be38816005427cca185)

Нужно реализовать класс, который бы позволил быстро и легко считывать данный в табличном виде
Данный класс пригодится для считывания информации о количестве и наполнении сцен

2023-05-20 16:21 UTC, Arugaf requested changes

2023-05-20 16:21 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/FileSystem/TableReader.hpp
> +        explicit TableReader(std::unique_ptr<std::istream>&& dataStream, const char separator = ' ');
Не надо передавать умные указатели по lvalue или rvalue ссылке. В этом нет смысла.

2023-05-20 16:21 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/FileSystem/TableReader.hpp
> +        explicit TableReader(std::unique_ptr<std::istream>&& dataStream, const char separator = ' ');
А почему вообще была выбрана передача `std::unique_ptr` на поток?

2023-05-20 16:21 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/FileSystem/TableReader.hpp
> +        explicit TableReader(std::unique_ptr<std::istream>&& dataStream, const char separator = ' ');
`separator` уже будет скопирован по значению при передаче в конструктор. Нет смысла помечать его `const`.

2023-05-20 16:21 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/FileSystem/TableReader.hpp
> +        [[nodiscard]] auto operator[](const keyType& key) const -> valueType;
Можно возвращать константную ссылку.

2023-05-20 16:21 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/FileSystem/TableReader.hpp
> +        [[nodiscard]] auto endOfStream() const -> bool;
Почему такое название метода?

2023-05-20 16:21 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/FileSystem/TableReader.hpp
> +        [[nodiscard]] auto is_ValuesReadable() const -> bool;
Почему нижнее подчеркивание? Такого вроде нигде нет в названиях методов.

2023-05-20 16:21 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/FileSystem/TableReader.hpp
> +}  // namespace AnimeDefendersEngine
Пустая строка потерялась.

2023-05-20 16:21 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/FileSystem/TableReader.cpp
> +        if (m_dataStream->eof()) {
Соответствующий метод вызывать?

2023-05-20 16:21 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/FileSystem/TableReader.cpp
> +    if (!(*m_dataStream).good() || (*m_dataStream).eof()) {
Почему бы не использовать `->`?

2023-05-20 16:21 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/FileSystem/TableReader.cpp
> +    auto splitedString = SplitString(line, m_wordsInRowSeparator);
`const auto`

2023-05-21 13:54 UTC, MiraiRatchet commented on libs/AnimeDefendersEngine/src/FileSystem/TableReader.cpp
> +}
Подушню про пустую строку

2023-05-21 14:10 UTC, MiraiRatchet commented on libs/AnimeDefendersEngine/src/FileSystem/TableReader.cpp
> +using AnimeDefendersEngine::TableReader;
Вроде просили не юзать using ..., хотя раз сам Арсений это не отметил, то видимо без разницы?...

2023-05-21 14:11 UTC, MiraiRatchet requested changes
Кросивое

2023-05-23 07:09 UTC, BorisKaryshev commented on libs/AnimeDefendersEngine/include/FileSystem/TableReader.hpp
> +        explicit TableReader(std::unique_ptr<std::istream>&& dataStream, const char separator = ' ');
Чтобы `TableReader` владел потоком и никто кроме него не мог считывать из него т.к. это может сломать `TableReader`

2023-05-23 07:39 UTC, BorisKaryshev commented on libs/AnimeDefendersEngine/src/FileSystem/TableReader.cpp
> +        if (m_dataStream->eof()) {
Какой? 
Я не смог найти...

2023-05-23 13:55 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/FileSystem/TableReader.cpp
> +        if (m_dataStream->eof()) {
Был nit по сути.

2023-05-23 13:55 UTC, Arugaf approved these changes, later dismissed
В целом норм.

2023-05-23 14:15 UTC, MiraiRatchet submitted a review, later dismissed

2023-05-23 14:23 UTC, merged