[ADEF-BBS-048] Math: Implement 2D matrix
cpp-park-vk-education/2023_1_Japanese_gardens_and_landscapes pull request #18
Opened 2023-05-20 11:54 UTC by BorisKaryshev

[Таск](https://flat-bottle-4d0.notion.site/Matrix2d-36a1b17ba8a44bf698af5ceccc64fb4a)

2023-05-20 16:03 UTC, Arugaf requested changes

2023-05-20 16:03 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/Math/Matrix2d.hpp
> +#include <iostream>
Почему отделены пустой строкой?

2023-05-20 16:03 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/Math/Matrix2d.hpp
> +                std::ranges::copy(values, m_values.begin());
Конструктор принимает `values` по значению. То есть уже было одно копирование.

2023-05-20 16:03 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/Math/Matrix2d.hpp
> +             */
Покрывать документацией примитивные геттеры странно и не особо продуктивно.

2023-05-20 18:37 UTC, AngelicHedgehog requested changes
Больше ничего не нашёл

2023-05-20 18:37 UTC, AngelicHedgehog commented on libs/AnimeDefendersEngine/include/Math/Matrix2d.hpp
> +                : m_rows{rows}, m_columns{m_columns}, m_values(rows * columns, val) {}
Реализации методов в хедере
Хз, норм?

2023-05-21 12:56 UTC, AngelicHedgehog approved these changes, later dismissed
ок

2023-05-23 10:51 UTC, AngelicHedgehog approved these changes
ok

2023-05-23 14:01 UTC, Arugaf approved these changes
В целом конечно сойдет.. Не знаю, правда, насколько оправдано было делать отдельный класс под это, а не воспользоваться готовыми решениями.

Если подразумевалась работа с итераторами, то стоило делать соответствующие type traits и т.п.

2023-05-23 14:03 UTC, merged