[ADEF-BBS-043] Event System: Implement EventManager, Event, EventListener and InputManager
cpp-park-vk-education/2023_1_Japanese_gardens_and_landscapes pull request #19
Opened 2023-05-20 18:44 UTC by MiraiRatchet

Ссылка на таску: https://www.notion.so/8f95d2a794ea456c8f54250f5df2a48e?pvs=4
Реализуются компонента Event, менеджеры для Event System, листенеры для ивентов и мелкие исправления

2023-05-20 20:28 UTC, BorisKaryshev requested changes
Всё хорошо, но есть несколько мелких недочетов, не влияющих на функциональность программы, так что можешь на них закрыть глаза если хочешь

2023-05-20 20:28 UTC, BorisKaryshev commented on libs/AnimeDefendersEngine/include/AnimeFramework/Event.hpp
> +
Сначала публичные методы, потом публичные поля, потом протектед методы и т.д.
Т.е. лучше наверное расположить приватные поля после публичных методов

2023-05-20 20:28 UTC, BorisKaryshev commented on libs/AnimeDefendersEngine/include/AnimeFramework/Event.hpp
> +        Event(std::string name, EventType type, std::string add = "") : m_name(name), m_eventType(type), m_additional(add) {}
Строчки стоит передавать по ссылке, а не по значению

2023-05-20 20:28 UTC, BorisKaryshev commented on libs/AnimeDefendersEngine/include/AnimeFramework/EventListener.hpp
> +}  // namespace AnimeDefendersEngine
Нет пустой строчки в конце файла

2023-05-20 20:28 UTC, BorisKaryshev commented on libs/AnimeDefendersEngine/include/AnimeFramework/EventManager.hpp
> +        static auto hasEvent(std::string eventName) -> bool;
Опять, же стоит передавать по ссылке

2023-05-20 20:28 UTC, BorisKaryshev commented on libs/AnimeDefendersEngine/include/Graphics/IWindow.hpp
> +            virtual auto setWindowKeyboardListener(void (*)(unsigned char, int, int)) const -> void = 0;
Будет гораздо более читаемо если ввести синонимы для типов указателей

2023-05-20 20:28 UTC, BorisKaryshev commented on libs/AnimeDefendersEngine/include/OpenGlDependency/Window.hpp
> +            auto setWindowKeyboardListener(void (*)(unsigned char, int, int)) const -> void;
Аналогично, синонимы

2023-05-20 20:28 UTC, BorisKaryshev commented on libs/AnimeDefendersEngine/src/AnimeFramework/EventManager.cpp
> +auto EventManager::hasEvent(std::string eventName) -> bool {
Ссылка

2023-05-20 20:28 UTC, BorisKaryshev commented on libs/AnimeDefendersEngine/src/AnimeFramework/EventManager.cpp
> +    for (auto listener : eventListeners) {
Точно предполагается копирование элементов контейнера?

2023-05-20 20:28 UTC, BorisKaryshev commented on libs/AnimeDefendersEngine/src/AnimeFramework/InputManager.cpp
> +auto getButtonDown(unsigned char button) -> bool
`[[nodiscard]]`?

2023-05-20 20:28 UTC, BorisKaryshev commented on libs/AnimeDefendersEngine/include/AnimeFramework/InputManager.hpp
> +        auto mouseHandler(int, int, int, int) -> void;
По названиям аргументов не понятно их предназначение

2023-05-23 14:38 UTC, Arugaf requested changes

2023-05-23 14:38 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/AnimeFramework/Event.hpp
> +        None = 0,
Хочется явно видеть низлежащий тип.

2023-05-23 14:38 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/AnimeFramework/Event.hpp
> +        std::string m_additional{};
Для нетривиальных типов уже будет вызван дефолтный конструктор (при отсутствии инициализатора).

2023-05-23 14:38 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/AnimeFramework/Event.hpp
> +        Event(std::string name, EventType type, std::string add = "") : m_name(name), m_eventType(type), m_additional(add) {}
Либо использовать std::move в списке инициализации.

2023-05-23 14:38 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/AnimeFramework/Event.hpp
> +        auto getName() -> std::string { return m_name; }
`const` методы.

2023-05-23 14:38 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/AnimeFramework/Event.hpp
> +        auto getName() -> std::string { return m_name; }
`const std::string&` в качестве возвращаемого типа.

2023-05-23 14:38 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/AnimeFramework/EventListener.hpp
> +#include "Event.hpp"
Пустая строка.

2023-05-23 14:38 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/AnimeFramework/EventListener.hpp
> +    };
В отдельный файл.

2023-05-23 14:38 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/AnimeFramework/EventListener.hpp
> +    class EventListener : public IEventListener {
`final`

2023-05-23 14:38 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/AnimeFramework/EventManager.hpp
> +            auto getName() const -> std::string { return eventListenerName; }
`const std::string&` возвращаемый тип.

2023-05-23 14:38 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/AnimeFramework/EventManager.hpp
> +            explicit EventListener(const std::function<void()>& function, const std::string& name)
Что за `function`?

2023-05-23 14:38 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/AnimeFramework/EventManager.hpp
> +            friend bool operator==(const EventListener& lhs, const EventListener& rhs);
Зачем `friend`?

2023-05-23 14:38 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/AnimeFramework/EventManager.hpp
> +            auto function() -> std::function<void()> { return listenerFunction; }
Странное название метода.

2023-05-23 14:38 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/AnimeFramework/EventManager.hpp
> +            friend bool operator==(const EventListener& lhs, const EventListener& rhs);
Реализацию всех методов в `.cpp` файл.

2023-05-23 14:38 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/AnimeFramework/EventManager.hpp
> +        std::vector<std::unique_ptr<Event>> eventQueue{};
Все это вышло за пределы класса...

2023-05-23 14:38 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/AnimeFramework/InputManager.hpp
> +        auto getButtonDown(const unsigned char button) -> bool;
Почему не в отдельном классе?

2023-05-23 14:38 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/AnimeFramework/InputManager.hpp
> +        auto getButtonDown(const unsigned char button) -> bool;
Нет смысла в `const` для типа, передаваемого по значению.

2023-05-23 14:38 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/AnimeFramework/InputManager.hpp
> +            int y;
Дефолтные значения.

2023-05-23 14:38 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/Graphics/IWindow.hpp
> +            virtual auto setWindowKeyboardListener(void (*)(unsigned char, int, int)) const -> void = 0;
Не стоит в принципе использовать указатели на функцию. `std::function` и дать алиасы.

2023-05-23 14:38 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/OpenGlDependency/Window.hpp
> +            Window(int, int, const std::string&);
Непонятно что за аргументы.

2023-05-23 14:38 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/OpenGlDependency/Window.hpp
> +            ~Window();
`override`

2023-05-23 14:38 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/Graphics/IWindow.hpp
> +            virtual auto setWindowKeyboardListener(void (*)(unsigned char, int, int)) const -> void = 0;
**Виртуальный деструктор!**

2023-05-23 14:38 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/AnimeFramework/EventManager.cpp
> +    eventListeners.erase(std::find(eventListeners.begin(), eventListeners.end(), listener));
Зачем `std::find`?

2023-05-23 14:38 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/OpenGlDependency/Window.cpp
> +#include <memory>
Кастомные и стандартные хедеры отделяются пустой строкой.

2023-05-23 21:36 UTC, MiraiRatchet commented on libs/AnimeDefendersEngine/include/AnimeFramework/EventManager.hpp
> +        std::vector<std::unique_ptr<Event>> eventQueue{};
Это задумка художника (это должно быть в неймспейсе)

2023-05-24 18:44 UTC, Arugaf requested changes

2023-05-24 18:44 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/AnimeFramework/Event.hpp
> +        Event(const std::string& name, EventType type, const std::string& add) : m_name(name), m_eventType(type), m_additional(add) {}
Что за `add`? Может не стоит сокращать названия аргументов?

2023-05-24 18:44 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/AnimeFramework/EventListener.hpp
> +        explicit EventListener(const std::function<void()>& function, const std::string& name)
`explicit` не нужен.

2023-05-24 18:44 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/AnimeFramework/EventListener.hpp
> +        explicit EventListener(const std::function<void()>& function, const std::string& name)
Все еще непонятно что за `function`.

2023-05-24 18:44 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/AnimeFramework/EventListener.hpp
> +#include "Event.hpp"
Сначала свой хедер, затем библиотечный. Разделяется пустой строкой.

2023-05-24 18:44 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/AnimeFramework/EventManager.hpp
> +        std::vector<std::unique_ptr<Event>> eventQueue{};
Все еще непонятно почему данные не инкапсулированы в классе.

2023-05-24 18:44 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/AnimeFramework/EventManager.hpp
> +        std::vector<std::unique_ptr<Event>> eventQueue{};
Особенно вот эти глобальные переменные. В данном виде проект может просто напросто не скомпилиться. Об этом должны были говорить на лекциях. И я рассказывал об этом на семинаре.

2023-05-24 18:44 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/AnimeFramework/InputManager.hpp
> +#include "GL/glut.h"
Кажется, это хедер из другой библиотеки. Он должен быть отделен от своих хедеров. И подключаться должен в угловых скобках.

2023-05-24 18:44 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/AnimeFramework/InputManager.hpp
> +        auto keyboardHandler(unsigned char key, int x, int y) -> void;
Что такое `x` и `y`?

2023-05-24 18:44 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/AnimeFramework/InputManager.hpp
> +        auto mouseHandler(int, int, int, int) -> void;
Что за непонятные аргументы?

2023-05-24 18:44 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/AnimeFramework/InputManager.hpp
> +        auto getButtonDown(unsigned char button) -> bool;
Почему все опять вне класса?

2023-05-24 18:44 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/AnimeFramework/EventListener.cpp
> +    auto EventListener::getFunction() -> std::function<void()> {
Потерялась разделяющая пустая строка.

2023-05-24 18:44 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/AnimeFramework/EventManager.cpp
> +}  // namespace AnimeDefendersEngine
Потерялась пустая строка в конце.

2023-05-24 19:21 UTC, BorisKaryshev requested changes

2023-05-24 19:21 UTC, BorisKaryshev commented on libs/AnimeDefendersEngine/include/AnimeFramework/Event.hpp
> +        auto getName() const -> const std::string& { return m_name; }
`[[nodsicard]]`?

2023-05-24 19:21 UTC, BorisKaryshev commented on libs/AnimeDefendersEngine/include/AnimeFramework/Event.hpp
> +        auto getType() const -> EventType { return m_eventType; }
`const`?
`[[nodsicard]]`?

2023-05-24 19:21 UTC, BorisKaryshev commented on libs/AnimeDefendersEngine/include/AnimeFramework/EventListener.hpp
> +        auto getFunction() -> std::function<void()>;
`[[nodsicard]]`?

2023-05-24 19:21 UTC, BorisKaryshev commented on libs/AnimeDefendersEngine/include/AnimeFramework/EventListener.hpp
> +        std::function<void()> listenerFunction;
Префикс `m_` перед названием приватных полей

2023-05-24 19:21 UTC, BorisKaryshev commented on libs/AnimeDefendersEngine/include/AnimeFramework/InputManager.hpp
> +            int y{0};
Может проще `MousePosition(int x = 0, int y = 0)`?

2023-05-24 19:21 UTC, BorisKaryshev commented on libs/AnimeDefendersEngine/include/AnimeFramework/EventManager.hpp
> +        auto operator==(const EventListener& lhs, const EventListener& rhs) -> bool;
`[[nodiscard]]`

2023-05-24 19:21 UTC, BorisKaryshev commented on libs/AnimeDefendersEngine/include/AnimeFramework/EventManager.hpp
> +        auto hasEvent(const std::string& eventName) -> bool;
`[[nodiscard]]`

2023-05-24 19:21 UTC, BorisKaryshev commented on run.sh
> +./build/AnimeDefenders
Этого файла быть не должно

2023-05-28 18:39 UTC, BorisKaryshev requested changes
В целом норм, но кое что нужно поправить

2023-05-28 18:39 UTC, BorisKaryshev commented on libs/AnimeDefendersEngine/include/AnimeFramework/Event.hpp
> +        EventType m_eventType{};
Может лучше явно указать дефолтное значение `EventType::None`?

2023-05-28 18:39 UTC, BorisKaryshev commented on libs/AnimeDefendersEngine/include/AnimeFramework/EventListener.hpp
> +    class EventListener {
Нет пустой строки

2023-05-28 18:39 UTC, BorisKaryshev commented on libs/AnimeDefendersEngine/include/AnimeFramework/EventManager.hpp
>      };
Нет пустой строки

2023-05-28 18:39 UTC, BorisKaryshev commented on libs/AnimeDefendersEngine/include/AnimeFramework/InputManager.hpp
> +        }
Почему не в `.cpp`?

2023-05-28 18:39 UTC, BorisKaryshev commented on libs/AnimeDefendersEngine/src/AnimeFramework/EventListener.cpp
> +        return (*this).getName() == rhs.getName();
`this->getName()`

2023-05-28 18:39 UTC, BorisKaryshev commented on libs/AnimeDefendersEngine/src/AnimeFramework/InputManager.cpp
> +    }
А чего реализации пустые?

2023-05-28 18:39 UTC, BorisKaryshev commented on libs/AnimeDefendersEngine/src/OpenGlDependency/Window.cpp
> +}
Синонимов очень не хватает

2023-05-28 18:39 UTC, BorisKaryshev commented on libs/AnimeDefendersEngine/src/AnimeFramework/InputManager.cpp
> +        auto event = std::make_unique<Event>("Mouse " + xMousePosition + " " + yMousePosition, EventType::MouseMoved);
Оператор + для строк в С стиле и чисел не определён. 
Чтобы исправить можно заменить на 

`"Mouse " + std::to_string(xMousePosition) + " " + std::to_string(yMousePosition)`

2023-05-28 18:41 UTC, Arugaf submitted a review, later dismissed
Есть довольно большие вопросы (в особенности из-за того, что потерялись интерфейсы, но в целом сойдет...

2023-05-28 18:42 UTC, BorisKaryshev commented on libs/AnimeDefendersEngine/src/AnimeFramework/InputManager.cpp
> +        auto event = std::make_unique<Event>("Mouse " + xMousePosition + " " + yMousePosition, EventType::MouseMoved);
А ещё, кажется конструктор `Event` принимает 3 аргумента, а не 2

2023-05-28 20:58 UTC, DPeshkoff submitted a review, later dismissed

2023-05-28 20:58 UTC, DPeshkoff commented on libs/AnimeDefendersEngine/include/AnimeFramework/Event.hpp
> +        [[nodiscard]] auto getType() const -> EventType { return m_eventType; }
Чисто стилистически разнес бы на новые строчки, но не критично.

Вообще интересно, что вы выбрали trailing return type, Гугл в своих гайдах [не рекомендует это](https://google.github.io/styleguide/cppguide.html#trailing_return) (если не говорим про лямбда-функции или особые кейсы)

2023-05-28 20:58 UTC, DPeshkoff commented on libs/AnimeDefendersEngine/src/AnimeFramework/EventListener.cpp
> +    auto EventListener::getName() const -> const std::string& {
Вообще формально можно сказать, что подпадает под [C.131](http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#c131-avoid-trivial-getters-and-setters). Но с другой стороны, на структуру тоже не особо катит. Но ознакомьтесь, полезно)

2023-05-29 12:38 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/AnimeFramework/Event.hpp
> +        [[nodiscard]] auto getType() const -> EventType { return m_eventType; }
У гугла много своих специфичных решений. Не стал бы опираться на него как на абсолютную истину.

В rust, к примеру, используется именно такая нотация. У го, в целом, тоже очень похожая.

2023-05-30 11:19 UTC, DPeshkoff commented on libs/AnimeDefendersEngine/include/AnimeFramework/Event.hpp
> +        [[nodiscard]] auto getType() const -> EventType { return m_eventType; }
Мы здесь не пишем на rust и go)

Не абсолютная истина, но слепо писать так тоже не стоит, доводы у Гугла логичные.

Понятно, что переписывать не предлагаю, это чтобы студенты знали, как это используют другие)

2023-05-30 14:10 UTC, Arugaf approved these changes

2023-05-31 18:32 UTC, BorisKaryshev approved these changes
LGTM

2023-05-31 18:32 UTC, BorisKaryshev commented on libs/AnimeDefendersEngine/src/AnimeFramework/EventManager.cpp
> +            if (eventName.rfind(event->getName(), 0) == 0) {
nit: магические числа. Ещё мне не очень понятно что делает эта строчка.

2023-05-31 18:32 UTC, BorisKaryshev commented on libs/AnimeDefendersEngine/src/AnimeFramework/InputManager.cpp
> +        });
nit: может вынести в именованные переменные? Мне кажется, так читать было бы проще

2023-05-31 18:59 UTC, merged