[ADEF-BBS-012] Graphics: OpenGL dependency: ITransposeMathWrapper impl
cpp-park-vk-education/2023_1_Japanese_gardens_and_landscapes pull request #24
Opened 2023-05-22 19:09 UTC by AngelicHedgehog

[Ссылка на таск](https://flat-bottle-4d0.notion.site/ITransposeMathWrapper-d86b02b245a44721a416e090c3fe3228)
Требуется реализовать интерфейс ITransposeMathWrapper с зависимостью от библиотеки OpenGL вместе с проработкой структуры Transpose

2023-05-23 22:22 UTC, Arugaf requested changes

2023-05-23 22:22 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/OpenGlDependency/TransposeMathWrapper.cpp
> +    auto TransposeMathWrapper::applyTransposeMatrix(const Math::Transpose* transpose) const noexcept -> void {
Почему по указателю, а не ссылке?

Нет даже проверки на валидность указателя.

2023-05-24 08:32 UTC, GoshaSerbin approved these changes, later dismissed

2023-05-24 18:46 UTC, Arugaf approved these changes
Сойдет.

2023-05-24 18:49 UTC, GoshaSerbin approved these changes

2023-05-24 18:55 UTC, merged