[ADEF-BBS-013] Graphics: OpenGl dependency: IDrawTextureWrapper imlp
cpp-park-vk-education/2023_1_Japanese_gardens_and_landscapes pull request #25
Opened 2023-05-22 19:10 UTC by AngelicHedgehog

[Ссылка на таск](https://flat-bottle-4d0.notion.site/IDrawTextureWrapper-b4733756d6b14d50b82f289baedbbe12)
Требуется реализовать интерфейс IDrawTextureWrapper с зависимостью от библиотеки OpenGL

2023-05-23 22:25 UTC, Arugaf requested changes

2023-05-23 22:25 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/Graphics/Texture.hpp
> +        unsigned int textureId{};
`size_t`?

2023-05-23 22:25 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/Graphics/Texture.hpp
> +        static constexpr std::array<float, 8> textureCoords{0, 0, 1, 0, 1, 1, 0, 1};
Непонятно откуда именно такие значения.

2023-05-23 22:25 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/Graphics/Texture.hpp
> +        static constexpr std::array<float, 8> textureCoords{0, 0, 1, 0, 1, 1, 0, 1};
Почему вообще `static`?

2023-05-23 22:25 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/OpenGlDependency/DrawTextureWrapper.hpp
> +        [[nodiscard]] auto loadTexture(const Math::Matrix2d<Color>&) const noexcept -> Texture override;
Не до конца понятно что конкретно такое `Math::Matrix2d<Color>`.

2023-05-23 22:27 UTC, AngelicHedgehog commented on libs/AnimeDefendersEngine/include/Graphics/Texture.hpp
> +        unsigned int textureId{};
Нет, так как сам opegl генерирует id для текстурки и его принимает именно в типе uint

2023-05-24 00:34 UTC, BorisKaryshev requested changes
В целом круто, но, кажется, есть места, где можно улучшить

2023-05-24 00:34 UTC, BorisKaryshev commented on libs/AnimeDefendersEngine/include/Graphics/IDrawTextureWrapper.hpp
> +        virtual auto loadTexture(const Math::Matrix2d<Color>& pixelMatrix) const noexcept -> Texture = 0;
`[[nodiscard]]`?

2023-05-24 00:34 UTC, BorisKaryshev commented on libs/AnimeDefendersEngine/src/OpenGlDependency/DrawTextureWrapper.cpp
> +        glTexCoordPointer(2, GL_FLOAT, 0, &*Texture::textureCoords.begin());
У `array` есть метод `data()`, который возвращает указатель на массив

2023-05-24 00:34 UTC, BorisKaryshev commented on libs/AnimeDefendersEngine/include/Graphics/IDrawTextureWrapper.hpp
> +        virtual auto loadTexture(const Math::Matrix2d<Color>& pixelMatrix) const noexcept -> Texture = 0;
`FileSystem::Image` теперь синоним для `Math::Matrix2d<Color>`, так что можно его вернуть

2023-05-24 00:34 UTC, BorisKaryshev commented on libs/AnimeDefendersEngine/src/OpenGlDependency/DrawTextureWrapper.cpp
> +    auto DrawTextureWrapper::loadTexture(const Math::Matrix2d<Color>& pixelMatrix) const noexcept -> Texture {
Тут точно не нужен `[[nodiscard]]`?

2023-05-24 00:53 UTC, AngelicHedgehog commented on libs/AnimeDefendersEngine/src/OpenGlDependency/DrawTextureWrapper.cpp
> +    auto DrawTextureWrapper::loadTexture(const Math::Matrix2d<Color>& pixelMatrix) const noexcept -> Texture {
В реализации аттрибуты не имеют силы

2023-05-24 00:57 UTC, AngelicHedgehog commented on libs/AnimeDefendersEngine/include/Graphics/IDrawTextureWrapper.hpp
> +        virtual auto loadTexture(const Math::Matrix2d<Color>& pixelMatrix) const noexcept -> Texture = 0;
Хорошо, если не забуду, позже сменю. Нет времени ждать, пока вы вольёте эти изменения в main, я считаю

2023-05-24 07:48 UTC, BorisKaryshev submitted a review, later dismissed
Вполне неплохо

2023-05-24 07:48 UTC, BorisKaryshev commented on libs/AnimeDefendersEngine/include/Graphics/IDrawTextureWrapper.hpp
> +        virtual auto drawTexture(const Texture&) const noexcept -> void = 0;
Виртуальный деструктор?

Я понимаю что класс не содержит данных, так что не критично, но всё же если есть время/силы было бы неплохо

2023-05-24 18:48 UTC, Arugaf approved these changes
Ничерта не понял в `DrawTextureWrapper.cpp`. Ok, I guess?

2023-05-24 19:03 UTC, BorisKaryshev approved these changes
LGTM

2023-05-24 19:05 UTC, merged