[ADEF-BBS-015] Graphics: Sprite: System and components definision
cpp-park-vk-education/2023_1_Japanese_gardens_and_landscapes pull request #26
Opened 2023-05-22 19:11 UTC by AngelicHedgehog

[Ссылка на таск](https://flat-bottle-4d0.notion.site/Sprite-Camera-f220d77f53ae4fa5a31547f59bed9184)
Необходимо реализовать систему по обработке данных Sprite-компоненты, а конкретно, описать метод drawSprite с использованием интерфейсов ITrasposeMathWrapper и IDrawTextureWrapper

2023-05-25 02:56 UTC, Arugaf requested changes

2023-05-25 02:56 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/SpriteComponent/Sprite.hpp
> +        explicit Sprite(const std::string& entityId, ComponentManager&, const Math::Transpose&, const Texture&) noexcept;
nit: `explicit` не нужен.

2023-05-25 02:56 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/SpriteComponent/Sprite.hpp
> +    class Sprite final : public BaseComponent<Sprite> {
А чего, crtp запилили? Жуки.

2023-05-25 02:56 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/SpriteComponent/SpriteSystem.cpp
> +        const DrawTextureWrapper drawTextureWrapper{};
`constexpr`? Если сами классы могут быть constexpr (а кажется, что могут).

2023-05-25 02:56 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/SpriteComponent/SpriteSystem.cpp
> +        const DrawTextureWrapper drawTextureWrapper{};
Вынести в анонимный неймспейс за пределами неймспейса, открывающегося выше.

2023-05-25 09:22 UTC, AngelicHedgehog commented on libs/AnimeDefendersEngine/include/SpriteComponent/Sprite.hpp
> +        explicit Sprite(const std::string& entityId, ComponentManager&, const Math::Transpose&, const Texture&) noexcept;
Жеесть, такое бывает? 🤯

2023-05-25 09:25 UTC, AngelicHedgehog commented on libs/AnimeDefendersEngine/src/SpriteComponent/SpriteSystem.cpp
> +        const DrawTextureWrapper drawTextureWrapper{};
Нет, не могут, проверял вот [здесь](https://github.com/cpp-park-vk-education/2023_1_Japanese_gardens_and_landscapes/pull/28/commits/89b83ff03eb69e99bba73407fa0844962b017c4f#:~:text=namespace%20%7B-,constexpr%20TransposeMathWrapper%20transposeMathWrapper%3B,-Check%20failure%20on) (и отсутствие скобок инициализации здесь совсем ни при чём)

2023-05-25 09:28 UTC, AngelicHedgehog commented on libs/AnimeDefendersEngine/src/SpriteComponent/SpriteSystem.cpp
> +        const DrawTextureWrapper drawTextureWrapper{};
Так они уже в анонимном неймспейсе... 👀
Или нужен ещё один............... 👀👀👀

2023-05-28 18:44 UTC, Arugaf approved these changes

2023-05-28 18:44 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/SpriteComponent/SpriteSystem.cpp
> +        auto texture = sprite->getTexture();
nit: `const auto`.

2023-05-28 18:55 UTC, MiraiRatchet approved these changes
Красиво

2023-05-28 18:55 UTC, merged