[ADEF-BBS-024] Graphics: OpenGL dependency: IWindow implementation
cpp-park-vk-education/2023_1_Japanese_gardens_and_landscapes pull request #27
Opened 2023-05-22 19:13 UTC by AngelicHedgehog

[Ссылка на таск](https://flat-bottle-4d0.notion.site/IWindow-OpenGL-dc7a434e3f0e408f801c7a4f5556d623)
Необходимо реализовать все методы интерфейса IWindow через функционал библиотеки OpenGL

2023-05-23 22:27 UTC, Arugaf requested changes

2023-05-23 22:27 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/Graphics/IWindow.hpp
> +        virtual auto setWindowKeyboardHandler(std::function<void(unsigned char, int, int)>) const noexcept -> void = 0;
Предлагаю завести алиасы на функторы. А то вообще непонятно что они делают.

2023-05-23 22:27 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/Graphics/IWindow.hpp
> +        virtual auto updateFrame() const noexcept -> void = 0;
Виртуальный деструктор.

2023-05-24 09:52 UTC, MiraiRatchet requested changes

2023-05-24 09:52 UTC, MiraiRatchet commented on libs/AnimeDefendersEngine/include/Graphics/IWindow.hpp
> +        virtual auto isShiftPressd() const noexcept -> bool = 0;
Pressed

2023-05-24 09:52 UTC, MiraiRatchet commented on libs/AnimeDefendersEngine/src/OpenGlDependency/Window.cpp
> +    }
Добавь, пожалуйста, еще хэндлер для glutPassiveMotionFunc

2023-05-24 09:52 UTC, MiraiRatchet commented on libs/AnimeDefendersEngine/include/OpenGlDependency/Window.hpp
> +        int m_windowHeidth{};
и все таки height :c

2023-05-24 13:44 UTC, MiraiRatchet requested changes

2023-05-24 13:44 UTC, MiraiRatchet commented on libs/AnimeDefendersEngine/src/OpenGlDependency/Window.cpp
> +        glutMotionFunc(handler.target<void(int, int)>());
Ты случайно 2 штуки MotionFunc поставил

2023-05-24 13:44 UTC, MiraiRatchet commented on libs/AnimeDefendersEngine/include/Graphics/IWindow.hpp
> +}  // namespace AnimeDefendersEngine::Graphics
Пустые строчки

2023-05-24 18:51 UTC, Arugaf approved these changes
Не понял почему на клавиши ctrl, shift, alt свои отслеживающие методы есть. В остальном норм.

2023-05-24 19:05 UTC, MiraiRatchet approved these changes
Красиво

2023-05-24 19:10 UTC, merged