[ADEF-BBS-015] Graphics: Camera: System and components definision
cpp-park-vk-education/2023_1_Japanese_gardens_and_landscapes pull request #28
Opened 2023-05-22 19:15 UTC by AngelicHedgehog

[Ссылка на таск](https://flat-bottle-4d0.notion.site/Camera-29996421d42a4ea9a9e627642ac10f79)
Необходимо реализовать систему по обработке информации о Camera-компоненте: расчёт новой позиции через motionRule, поправка положения по extraMotion, определение финального положения в cameraTranspose

2023-05-25 02:48 UTC, Arugaf requested changes

2023-05-25 02:48 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/CameraComponent/Camera.hpp
> +        explicit Camera(const std::string& entityId, ComponentManager&, const Math::Transpose&,
`explicit` лишний.

2023-05-25 02:48 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/CameraComponent/Camera.hpp
> +        std::function<void(Math::Transpose&)> m_extraMotion;
Завести алиасы.

2023-05-25 02:48 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/CameraComponent/CameraSystem.hpp
> +    auto applyCameraView(const Camera*) -> void;
?

2023-05-25 02:48 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/CameraComponent/Camera.cpp
> +        m_extraMotion(m_transpose);
В названиях полей, кажется, не хватает явного указания, что это функтор.

2023-05-25 02:48 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/CameraComponent/Camera.cpp
> +        CameraSystem::applyCameraView(this);
Заглушка?

2023-05-25 09:28 UTC, AngelicHedgehog commented on libs/AnimeDefendersEngine/include/CameraComponent/Camera.hpp
> +        explicit Camera(const std::string& entityId, ComponentManager&, const Math::Transpose&,
лладно, думал, таких ситуаций не бывает........

2023-05-25 09:29 UTC, AngelicHedgehog commented on libs/AnimeDefendersEngine/include/CameraComponent/CameraSystem.hpp
> +    auto applyCameraView(const Camera*) -> void;
что "?"?

2023-05-25 09:29 UTC, AngelicHedgehog commented on libs/AnimeDefendersEngine/src/CameraComponent/Camera.cpp
> +        CameraSystem::applyCameraView(this);
Нет, всего лишь вынесение логики.

2023-05-25 10:05 UTC, AngelicHedgehog commented on libs/AnimeDefendersEngine/include/CameraComponent/CameraSystem.hpp
> +    auto applyCameraView(const Camera*) -> void;
![image](https://github.com/cpp-park-vk-education/2023_1_Japanese_gardens_and_landscapes/assets/102258145/ae31572c-42c7-4435-ba65-40b602354e95)

2023-05-25 12:02 UTC, Arugaf requested changes

2023-05-25 12:02 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/CameraComponent/Camera.hpp
> +    using transposeChangingFunc = std::function<void(Math::Transpose&)>;
Нейминг - не надо сокращать. Советую оставить Functor в конце.

2023-05-25 12:02 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/CameraComponent/Camera.hpp
> +        transposeChangingFunc m_extraMotionFunc;
Нейминг.

2023-05-25 12:02 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/CameraComponent/Camera.hpp
> +    using transposeChangingFunc = std::function<void(Math::Transpose&)>;
Засунуть в класс вместо неймспейса.

2023-05-25 12:02 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/CameraComponent/Camera.cpp
> +        std::function<void(Math::Transpose&)> extraMotionFunc = [](Math::Transpose&) {}, bool isActive = true) noexcept
Алиасы.

2023-05-25 12:02 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/CameraComponent/Camera.hpp
> +               std::function<void(Math::Transpose&)> extraMotion, bool isActive) noexcept;
Алиасы.

2023-05-25 12:02 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/CameraComponent/CameraSystem.cpp
> +    }
`//  namespace`

2023-05-28 18:47 UTC, Arugaf requested changes

2023-05-28 18:47 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/CameraComponent/Camera.hpp
> +        auto setIsActive(bool) noexcept -> void;
`setActive`

2023-05-28 19:08 UTC, Arugaf approved these changes

2023-05-28 19:11 UTC, GoshaSerbin approved these changes
LGTM

2023-05-28 19:21 UTC, merged