[ADEF-BBS-003] Physics: Physics World: Impelement physics world
cpp-park-vk-education/2023_1_Japanese_gardens_and_landscapes pull request #32
Opened 2023-05-23 09:51 UTC by GoshaSerbin

[ссылка на таск](https://flat-bottle-4d0.notion.site/PhysicsWorld-570479f1165e4ab393c2b03bc5adab33)

Реализовать класс Physics World, который с помощью CollisionHandler определяет новые положения тел и генерирует список произошедших  за шаг моделирования событий

2023-05-23 14:11 UTC, Arugaf requested changes

2023-05-23 14:11 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/Physics/ContactEvent.hpp
> +}  // namespace AnimeDefendersEngine::Physics
Потерялась пустая строка.

2023-05-23 14:11 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/Physics/PhysicsWorld.hpp
> +        float m_maxDeltaTime;
Дефолтные значения!

2023-05-23 14:11 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/Physics/Manifold.cpp
> +               left.bodyA->getID() == right.bodyB->getID() && left.bodyB->getID() == right.bodyA->getID();
`std::tie`

2023-05-23 21:17 UTC, MiraiRatchet submitted a review, later dismissed

2023-05-23 23:10 UTC, Arugaf requested changes

2023-05-23 23:10 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/Physics/ContactEvent.hpp
> +        ContactEvent(std::string bodyAID, std::string bodyDID, ContactEventType type) : bodyAID(bodyAID), bodyBID(bodyBID), type(type){};
Строки точно должны передаваться по значению? Если да, то мувай их в списке инициализации.

2023-05-23 23:10 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/Physics/PhysicsWorld.hpp
> +    constexpr float defaultMinUpdateFrequency = 25.f;
Почему в теле класса?

2023-05-23 23:10 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/Physics/PhysicsWorld.hpp
> +                     float maxDeltaTime = 1.f / defaultMinUpdateFrequency);
Связано с предыдущим комментарием.

Предлагаю завести два конструктора: один с одним аргументом, другой с тремя. Перенести константы выше в анонимный неймспейс в `.cpp` файле. Использовать делегирующий конструктор с константами (которые уже будут учитывать то, что они в знаменателе, в частности).

2023-05-23 23:10 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/Physics/PhysicsWorld.hpp
>          std::unique_ptr<CollisionHandler> m_collisionHandler;
Отсюда снова добавить модификатор доступа, ибо поля пошли.

2023-05-23 23:10 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/Physics/PhysicsWorld.hpp
> +        float m_accumulator{0};
С учетом двух комментариев выше.

Оставить дефолтную инициализацию через `{}`.

2023-05-23 23:10 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/Physics/CollisionHandler.cpp
> +                if ((*bodyAIter)->getID() < (*bodyBIter)->getID()) {
А не можем ли тут выйти за пределы размера `bodies` и начать обращаться к `bodies.end()`?

2023-05-23 23:10 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/Physics/Manifold.cpp
> +    }
В анонимный неймспейс.

2023-05-23 23:10 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/Physics/Manifold.cpp
> +    auto operator==(const Manifold& left, const Manifold& right) -> bool {
Тоже заинлайнить.

2023-05-23 23:10 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/Physics/Manifold.cpp
> +    auto operator==(const Manifold& left, const Manifold& right) -> bool {
Можно не указывать возвращаемый тип.

2023-05-24 06:26 UTC, GoshaSerbin commented on libs/AnimeDefendersEngine/src/Physics/CollisionHandler.cpp
> +                if ((*bodyAIter)->getID() < (*bodyBIter)->getID()) {
Нет. Почему? В первом цикле фактически гарантируется что bodyAIter < bodies.end(). Второй итератор не может проскочить bodies.end, т.к. чтобы он проскочил нужно чтобы первый итератор = bodies.end(), что невозможно

2023-05-24 19:03 UTC, Arugaf requested changes

2023-05-24 19:03 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/Physics/BodyDefinition.hpp
> +                       const Math::Vector2f& velocity, float mass, std::size_t layers, const Math::Vector2f& force, bool isTrigger);
Math::Vector2f маленькая по размеру структура. Лучше ее копировать.

2023-05-24 19:03 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/Physics/BodyDefinition.hpp
> +                       const Math::Vector2f& velocity, float mass, std::size_t layers, const Math::Vector2f& force, bool isTrigger);
Лучше все аргументы тут размещать в отдельной строке.

2023-05-24 19:03 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/Physics/ContactEvent.hpp
> +        std::string bodyAID;
Предлагаю отделить хотя бы пустой строкой.

2023-05-24 19:03 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/Physics/ICollisionHandler.hpp
>          virtual auto resolveCollision(Manifold& contact) const -> void = 0;
Виртуальный деструктор!!!

2023-05-24 19:03 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/Physics/PhysicsWorld.hpp
> +        PhysicsWorld(std::unique_ptr<CollisionHandler> collisionHandler);
`explicit`

2023-05-24 19:03 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/Systems/SystemManager.hpp
>      };
В отдельный файл.

2023-05-24 19:03 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/Systems/SystemManager.hpp
> +        virtual void updateSystems(SceneManager&, float) = 0;
Непонятно что за второй аргумент.

2023-05-24 19:33 UTC, GoshaSerbin commented on libs/AnimeDefendersEngine/include/Physics/BodyDefinition.hpp
> +                       const Math::Vector2f& velocity, float mass, std::size_t layers, const Math::Vector2f& force, bool isTrigger);
Таск на изменение кланг-формат добавлен

2023-05-24 19:40 UTC, GoshaSerbin commented on libs/AnimeDefendersEngine/include/Physics/ICollisionHandler.hpp
>          virtual auto resolveCollision(Manifold& contact) const -> void = 0;
Так он тут есть
![image](https://github.com/cpp-park-vk-education/2023_1_Japanese_gardens_and_landscapes/assets/108980624/dbf5217e-a0d0-4203-b61d-e7542f6c09d3)

2023-05-24 19:42 UTC, GoshaSerbin commented on libs/AnimeDefendersEngine/include/Systems/SystemManager.hpp
>      };
В другой ветке сделаем

2023-05-24 19:51 UTC, Arugaf requested changes

2023-05-24 19:51 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/Physics/PhysicsWorld.cpp
> +        std::vector<ContactEvent> events;
`{}`

2023-05-24 19:51 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/Physics/PhysicsWorld.cpp
> +        std::vector<Body*> bodies;
`{}`

2023-05-25 02:45 UTC, Arugaf approved these changes

2023-05-25 02:45 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/Systems/ISystem.hpp
> +        virtual void updateSystem(SceneManager&) = 0;
Не чекать? Виртуальный деструктор.

2023-05-25 02:45 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/Systems/SystemManager.hpp
>      };
Не чекать? Виртуальный деструктор.

2023-05-25 05:16 UTC, GoshaSerbin commented on libs/AnimeDefendersEngine/include/Systems/ISystem.hpp
> +        virtual void updateSystem(SceneManager&) = 0;
Да

2023-05-25 05:17 UTC, GoshaSerbin commented on libs/AnimeDefendersEngine/include/Systems/SystemManager.hpp
>      };
Да

2023-05-25 07:56 UTC, MiraiRatchet approved these changes

2023-05-25 07:57 UTC, merged