[ADEF-BBS-049] Objects: Implement file system class which loads resources reqiered by game
cpp-park-vk-education/2023_1_Japanese_gardens_and_landscapes pull request #34
Opened 2023-05-24 09:51 UTC by BorisKaryshev

[Таск](https://flat-bottle-4d0.notion.site/FileSystem-894dc5bb92974fe6a5acf48a45d9cb44)

2023-05-24 13:46 UTC, MiraiRatchet submitted a review, later dismissed

2023-05-24 19:12 UTC, Arugaf requested changes

2023-05-24 19:12 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/FileSystem/FileSystem.hpp
> +inline auto absolutePath(const std::convertible_to<std::string> auto& x) -> std::string {
`std::filesystem::path`

2023-05-24 19:12 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/FileSystem/FileSystem.hpp
> +#endif
Может лучше макрос, настраиваемый на уровне CMake?

2023-05-24 19:12 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/FileSystem/FileSystem.hpp
> +inline auto absolutePath(const std::convertible_to<std::string> auto& x) -> std::string {
Что за `x`?

2023-05-24 19:12 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/FileSystem/FileSystem.hpp
> +    using Graphics::Color;
`using` на уровне хедера - не очень хорошо в таком контексте.

2023-05-24 19:12 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/FileSystem/FileSystem.hpp
> +        using Image = Math::Matrix2d<Color>;
Такой алиас, к примеру, куда более допустим.

2023-05-24 19:12 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/FileSystem/FileSystem.cpp
> +        auto returnPixel(unsigned char* data, std::size_t i, std::size_t j, std::size_t x, std::size_t channelCount) -> Color {
Что за `i`, `j`, `x`?

2023-05-24 19:12 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/FileSystem/FileSystem.cpp
> +#include "stb_image.h"
Привести в порядок.

2023-05-24 19:12 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/FileSystem/FileSystem.cpp
> +        auto returnPixel(unsigned char* data, std::size_t i, std::size_t j, std::size_t x, std::size_t channelCount) -> Color {
Кажется, что не очень удачное название функции?

2023-05-24 19:12 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/FileSystem/FileSystem.cpp
> +            Color pixel;
`{}`

2023-05-24 19:12 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/FileSystem/FileSystem.cpp
> +            const unsigned char* pixelOffset = data + (i + x * j) * channelCount;
Выглядит небезопасно.

2023-05-24 19:12 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/FileSystem/FileSystem.cpp
> +            m_paths[reader["Name"]] = absolutePath(reader["FilePath"]);
Хардкод. Хотя бы в анонимный неймспейс вынести функции геттеры для строк.

2023-05-24 19:12 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/FileSystem/FileSystem.cpp
> +            int x{}, y{}, comps{};
Каждая переменная на отдельной строке.

2023-05-24 19:12 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/FileSystem/FileSystem.cpp
> +        if (m_paths.at(name).extension().string() == ".png") {
Инвертировать условие? Если планируются еще типы файлов, то вынести обработку в отдельную функцию?

2023-05-24 19:12 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/FileSystem/FileSystem.cpp
> +            std::vector<Color> pixels;
`{}`

2023-05-24 19:12 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/FileSystem/FileSystem.cpp
> +            unsigned char* data = stbi_load(m_paths.at(name).c_str(), &x, &y, &comps, 0);
`const auto`

2023-05-24 19:12 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/FileSystem/FileSystem.cpp
> +            loadItem(name);
А если не получилось, то что дальше?

2023-05-24 19:23 UTC, BorisKaryshev commented on libs/AnimeDefendersEngine/include/FileSystem/FileSystem.hpp
> +#endif
Так и делается, эти строчки чтобы IntelliSense не ругался

2023-05-28 16:23 UTC, MiraiRatchet approved these changes, later dismissed

2023-05-28 18:57 UTC, Arugaf requested changes

2023-05-28 18:57 UTC, Arugaf commented on GameFiles/3.png
Не нужно тут.

2023-05-28 18:57 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/FileSystem/FileSystem.hpp
> +        };
Странно, что виртуальная файловая система знает о конкретных типах файлов. По-хорошему должен быть какой-то отдельный класс, который умел бы доставать из этой вфс нужные файлы по типу и, быть может, заставлять ее (вфс) заводить отдельный индекс для поиска таких файлов по маске расширения.

2023-05-28 18:57 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/Math/Matrix2d.hpp
> +            }
Точно нужно в этом пр?

2023-05-28 18:57 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/FileSystem/FileSystem.cpp
> +        const std::string filePathColumnName{"FilePath"};
std::string может быть `constexpr`.

2023-05-28 18:57 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/FileSystem/FileSystem.cpp
> +        constexpr Graphics::Color redPixel = {maxRedColorValue, minBlueColorValue, minGreenColorValue, minAlphaValue};
Почему только красный?

2023-05-28 18:57 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/FileSystem/FileSystem.cpp
> +        constexpr Graphics::Color redPixel = {maxRedColorValue, minBlueColorValue, minGreenColorValue, minAlphaValue};
Почему `redPixel`, вместо просто какого-нибудь `red`?

2023-05-28 18:57 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/FileSystem/FileSystem.cpp
> +            const unsigned char* pixelOffset = data + (rowIndex + numberOfRows * columnIndex) * channelCount;
В отдельную функцию в анонимном неймспейсе. С небольшим комментарием для пояснения работы.

2023-05-28 18:57 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/FileSystem/FileSystem.cpp
> +            return Image{width, height, std::move(pixels)};
`return {width, height, std::move(pixels)};`

2023-05-28 21:12 UTC, DPeshkoff requested changes

2023-05-28 21:12 UTC, DPeshkoff commented on libs/AnimeDefendersEngine/libs/stb/stb_image.h
Вообще, такие файлы в идеале должно быть оформлены как гит-модули и не попадать в ПР, потому что это не ваш код)

Но не критично

2023-05-28 21:12 UTC, DPeshkoff commented on libs/AnimeDefendersEngine/src/FileSystem/FileSystem.cpp
> +            for (int j = 0; j < y; ++j) {
А точно ли int?)

2023-05-28 21:12 UTC, DPeshkoff commented on GameFiles/resourceLocations.txt
> +Name|FilePath
А почему не json какой-нибудь?

2023-05-29 12:43 UTC, Arugaf commented on libs/AnimeDefendersEngine/libs/stb/stb_image.h
Так, блин, а как я пропустил это. ИСПРАВИТЬ!

2023-05-30 06:11 UTC, BorisKaryshev commented on libs/AnimeDefendersEngine/src/FileSystem/FileSystem.cpp
> +            for (int j = 0; j < y; ++j) {
Точно, т.к. `stbi_load(...)`, считывающая изображение возвращает её размер именно как `int`

2023-05-30 06:12 UTC, BorisKaryshev commented on GameFiles/resourceLocations.txt
> +Name|FilePath
Нужно думать, а у нас времени мало (сил ещё меньше)
А считывание таблицы я в ДЗ1 реализовывал

2023-05-30 06:19 UTC, BorisKaryshev commented on libs/AnimeDefendersEngine/include/FileSystem/FileSystem.hpp
> +        };
На самом деле, стоило наверное класс назвать `ResourceManager` или как-то так.
Планировалось, что через него можно считать любые изображения в одном формате. 

Так что разделять файлы по из разрешению не вижу смысла.
Времени мало, мб потом разделю `ResourceManager` и вфс

2023-05-30 06:24 UTC, BorisKaryshev commented on libs/AnimeDefendersEngine/src/FileSystem/FileSystem.cpp
> +        const std::string filePathColumnName{"FilePath"};
Строчки используются в рантайме, так что не может

2023-05-30 06:26 UTC, BorisKaryshev commented on libs/AnimeDefendersEngine/src/FileSystem/FileSystem.cpp
> +        constexpr Graphics::Color redPixel = {maxRedColorValue, minBlueColorValue, minGreenColorValue, minAlphaValue};
Ну не голубой же

Нужен был какой-нибудь цвет для текстуры - "ошибки"
В тех играх, что я играл обычно для этих целей используют красный, а поскольку рисовать что-то сложное мне лень, то будет просто красный квадрат

2023-05-30 06:30 UTC, BorisKaryshev commented on libs/AnimeDefendersEngine/include/Math/Matrix2d.hpp
> +            }
Нет, но создавать новый/открывать старый ради 6 строк как то слишком как мне кажется

2023-05-30 09:41 UTC, Arugaf approved these changes

2023-05-31 18:19 UTC, MiraiRatchet approved these changes
Кайф

2023-05-31 18:22 UTC, merged