[ADEF-BBS-004] Physics: Physics System implementation
cpp-park-vk-education/2023_1_Japanese_gardens_and_landscapes pull request #36
Opened 2023-05-24 11:45 UTC by GoshaSerbin

[ссылка на таск](https://flat-bottle-4d0.notion.site/PhysicsSystem-Collider-62327d8d59544b60a87e13297b7dc406)

Реализовать физическую систему и компоненты, необходимые для работы этой системы

2023-05-24 13:33 UTC, AngelicHedgehog requested changes
Ахуеть я накидал, сори если задушил, но там по мелочи (ну кроме сетгеттеров))

2023-05-24 13:33 UTC, AngelicHedgehog commented on libs/AnimeDefendersEngine/include/Physics/ColliderComponent.hpp
> +}  // namespace AnimeDefendersEngine
Пустая строка в eof

2023-05-24 13:33 UTC, AngelicHedgehog commented on libs/AnimeDefendersEngine/include/Physics/ColliderComponent.hpp
> +#include "Vector2.hpp"
Ощущение, что половину этих инклюдов можно опустить, так как они содержатся в других
К примеру, `Component.hpp` подключается в `BaseComponent.hpp`

2023-05-24 13:33 UTC, AngelicHedgehog commented on libs/AnimeDefendersEngine/include/Physics/PhysicsWorld.hpp
> +        float m_accumulator{0};
Если уж не ставишь дефолтное значение, то не ставь везде, и наоборот)

2023-05-24 13:33 UTC, AngelicHedgehog commented on libs/AnimeDefendersEngine/include/Physics/TransformComponent.hpp
> +#include "Component.hpp"
Не используется (`Component`)

2023-05-24 13:33 UTC, AngelicHedgehog commented on libs/AnimeDefendersEngine/src/Physics/ColliderComponent.cpp
> +#include "Vector2.hpp"
Почти все эти файлы уже подключены в хедере класса, нет смысла их дублировать

2023-05-24 13:33 UTC, AngelicHedgehog commented on libs/AnimeDefendersEngine/include/Physics/ColliderComponent.hpp
> +        float radius{};
![image](https://github.com/cpp-park-vk-education/2023_1_Japanese_gardens_and_landscapes/assets/102258145/7eb30e9a-8b16-4159-828a-d22eeaca382c)

2023-05-24 13:33 UTC, AngelicHedgehog commented on libs/AnimeDefendersEngine/include/Physics/ContactEvent.hpp
> +            : bodyAID(std::move(bodyAID)), bodyBID(std::move(bodyBID)), type(type){};
Не логичнее было бы принимать значение по константной ссылке и опустить `std::move`?

2023-05-24 13:33 UTC, AngelicHedgehog commented on libs/AnimeDefendersEngine/include/Physics/PhysicsSystem.hpp
> +        auto addBodies(ComponentManager::ComponentsContainer& components) -> std::vector<Body*>;
`[[nodiscard]]` и `const`?
Если точно уверен, что при игнорировании возврата метода смысл вызова функции не пропадает, то `[[maybe_unused]]`

2023-05-24 13:33 UTC, AngelicHedgehog commented on libs/AnimeDefendersEngine/src/Physics/PhysicsSystem.cpp
> +    }
Удобнее, когда порядки реализаций функций и их объявлений совпадают
(чек хедер)

2023-05-24 13:33 UTC, AngelicHedgehog commented on libs/AnimeDefendersEngine/src/Physics/PhysicsSystem.cpp
> +            Body* body = m_physicsWorld.addBody(std::move(bodyDef));
`auto*`

2023-05-24 13:33 UTC, AngelicHedgehog commented on libs/AnimeDefendersEngine/include/Physics/PhysicsWorld.hpp
> +        auto fixedUpdate() -> std::vector<ContactEvent>;
Опять же, либо `[[nodiscard]]` и `const`, либо `[[maybe_unused]]`

2023-05-24 13:33 UTC, AngelicHedgehog commented on libs/AnimeDefendersEngine/include/Physics/PhysicsWorld.hpp
> +#include <string>
В эттом файле сттроки не используюттся, ссссэр!

2023-05-24 13:33 UTC, AngelicHedgehog commented on libs/AnimeDefendersEngine/include/Physics/RigidBodyComponent.hpp
> +#include "Component.hpp"
Лишнее капельку

2023-05-24 13:33 UTC, AngelicHedgehog commented on libs/AnimeDefendersEngine/src/Physics/BodyDefinition.cpp
>      BodyDefinition::BodyDefinition(std::string id, std::unique_ptr<Shape> shape, BodyType bodyType, Transform transform,
А в чём трабл в передаче строки по конст ссылке?

2023-05-24 13:33 UTC, AngelicHedgehog commented on libs/AnimeDefendersEngine/src/Physics/ColliderComponent.cpp
> +          transformComponent(transformComponent) {
Вот из-за того, что это ссылка и она паблик, здесь реально лучше прислушаться к ворнингу...
Хотя, надеюсь, ты сделаешь поля приватными и накидаешь сеттеров и геттеров))

2023-05-24 13:33 UTC, AngelicHedgehog commented on libs/AnimeDefendersEngine/src/Physics/CollisionHandler.cpp
>              for (auto bodyBIter = bodyAIter + 1; bodyBIter != bodies.end(); ++bodyBIter) {
Вместо `Iter + 1` лучше использовать `std::next(Iter)`

2023-05-24 13:33 UTC, AngelicHedgehog commented on libs/AnimeDefendersEngine/include/Physics/CollisionHandler.hpp
>          virtual auto resolveCollision(Manifold& contact) const -> void override;
А почему методы виртуальными оставлены, хотя класс помечен как `final`?
Подозрительно.... (ಥ _ ಥ)

2023-05-24 13:33 UTC, AngelicHedgehog commented on libs/AnimeDefendersEngine/include/Physics/RigidBodyComponent.hpp
> +    constexpr float defaultMass = 1.f;
Может добавить анонимный неймспейс?

2023-05-24 13:33 UTC, AngelicHedgehog commented on libs/AnimeDefendersEngine/src/Physics/PhysicsSystem.cpp
>  #include "SceneManager.hpp"
Опять же, добрую половину этого можно опустить, так как в хедере она есть

2023-05-24 13:33 UTC, AngelicHedgehog commented on libs/AnimeDefendersEngine/src/Physics/PhysicsSystem.cpp
>  #include <memory>
Это, кстати, тоже можно опустить, по той же причине (уже подключено в хедере)

2023-05-24 13:33 UTC, AngelicHedgehog commented on libs/AnimeDefendersEngine/src/Physics/PhysicsSystem.cpp
> +        for (auto component : components) {
`const auto&`

2023-05-24 13:33 UTC, AngelicHedgehog commented on libs/AnimeDefendersEngine/src/Physics/PhysicsSystem.cpp
> +            auto collider = static_cast<ColliderComponent*>(component.second);
`auto*`

2023-05-24 13:33 UTC, AngelicHedgehog commented on libs/AnimeDefendersEngine/src/Physics/PhysicsSystem.cpp
> +            auto bodyB = static_cast<ColliderComponent*>(colliders.at(event.bodyBID));
Аналогично, `auto*`

2023-05-24 13:33 UTC, AngelicHedgehog commented on libs/AnimeDefendersEngine/src/Physics/PhysicsSystem.cpp
> +            static_cast<ColliderComponent*>(components.at(body->getID()))->transformComponent.position = body->getPosition();
Лучше разделить длинную строку на несколько более читаемых

2023-05-24 13:33 UTC, AngelicHedgehog commented on libs/AnimeDefendersEngine/src/Physics/PhysicsWorld.cpp
>      auto PhysicsWorld::addBody(BodyDefinition&& bodyDefinition) -> Body* {}
Ну поставь заглушечку, чтобы ворнинги глаза не мозолили, типа `return nullptr;` 🙏🙏🙏

2023-05-24 13:33 UTC, AngelicHedgehog commented on libs/AnimeDefendersEngine/src/Physics/PhysicsWorld.cpp
> +    auto PhysicsWorld::getEvents(std::unordered_set<Manifold> currentContacts) -> std::vector<ContactEvent> {}
Ведь не так много требуется, всего лишь `return {};`

2023-05-24 13:33 UTC, AngelicHedgehog commented on libs/AnimeDefendersEngine/src/Physics/PhysicsWorld.cpp
> +    auto PhysicsWorld::fixedUpdate() -> std::vector<ContactEvent> {}
Разве чего-то стоит какой-то маленький `return {};`?

2023-05-24 15:13 UTC, GoshaSerbin commented on libs/AnimeDefendersEngine/include/Physics/ColliderComponent.hpp
> +#include "Vector2.hpp"
С Compoonent.hpp согласен. А с остальным, мне казалось что это гуд практис,  включать все то что используется в файле, даже если оно неявно включено в другой инклюд

2023-05-24 15:19 UTC, GoshaSerbin commented on libs/AnimeDefendersEngine/include/Physics/PhysicsWorld.hpp
> +        float m_accumulator{0};
accumulator всегда имеет начальное значение ноль, это прям значение со смыслом. А остальные переменные инициализируются в конструкторе, поэтому мне показалось нелогичным указывать конкретное значение им

2023-05-24 15:21 UTC, AngelicHedgehog commented on libs/AnimeDefendersEngine/include/Physics/PhysicsWorld.hpp
> +        float m_accumulator{0};
Тогда кк

2023-05-24 15:49 UTC, GoshaSerbin commented on libs/AnimeDefendersEngine/include/Physics/ContactEvent.hpp
> +            : bodyAID(std::move(bodyAID)), bodyBID(std::move(bodyBID)), type(type){};
Да

2023-05-24 19:22 UTC, Arugaf requested changes

2023-05-24 19:22 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/Physics/ColliderComponent.hpp
> +                          RigidBodyComponent* rigidBodyComponent = nullptr);
Каждый аргумент на отдельной строке.

2023-05-24 19:22 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/Physics/PhysicsWorld.hpp
> +        PhysicsWorld(std::unique_ptr<CollisionHandler> collisionHandler);
`explicit`

2023-05-24 19:22 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/Physics/RigidBodyComponent.hpp
> +        float mass;
`{}`

2023-05-24 19:22 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/Physics/PhysicsSystem.cpp
> +            BodyDefinition bodyDef;
`{}`

2023-05-24 19:22 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/Physics/PhysicsSystem.cpp
> +        std::vector<Body*> bodies;
`{}`

2023-05-24 19:22 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/Physics/PhysicsSystem.cpp
> +            }
Странная логика.

2023-05-24 19:22 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/Physics/PhysicsSystem.cpp
> +            }
Сделать `switch` `case`?

2023-05-24 19:46 UTC, GoshaSerbin commented on libs/AnimeDefendersEngine/include/Physics/ColliderComponent.hpp
> +                          RigidBodyComponent* rigidBodyComponent = nullptr);
Таск на изменения стиля создан

2023-05-25 10:25 UTC, AngelicHedgehog approved these changes
lgfm

2023-05-28 18:58 UTC, Arugaf approved these changes
LGTM

2023-05-28 19:04 UTC, merged