[ADEF-BBS-035] Objects: Implement class which loads entities on scene
cpp-park-vk-education/2023_1_Japanese_gardens_and_landscapes pull request #37
Opened 2023-05-28 13:22 UTC by BorisKaryshev

[Таск](https://www.notion.so/3d3059a072504076b6f6d8f661a7cc2b?pvs=4)

2023-05-28 13:48 UTC, AngelicHedgehog approved these changes, later dismissed
Совсем капельку накидал, да и те не критичны, так что на опережение аппруф

2023-05-28 13:48 UTC, AngelicHedgehog commented on libs/AnimeDefendersEngine/include/FileSystem/TableReader.hpp
> +        [[nodiscard]] auto splitString(const std::string& str, const char separator) -> std::vector<std::string>;
а к чему делать константный `char`, если это не указатель и не ссылка? Чтобы в теле метода нельзя было изменять? А смысл?

2023-05-28 13:48 UTC, AngelicHedgehog commented on libs/AnimeDefendersEngine/include/FileSystem/TableReader.hpp
>      }  // namespace FileSystem
Неймспейсы можно объединить

2023-05-28 13:48 UTC, AngelicHedgehog commented on libs/AnimeDefendersEngine/include/FileSystem/TableReader.hpp
>          };
я понимаю, что это старый и уже ободренный код, но ощущение, что у некоторых методов, таких как `isValuesReadable` не хватает суффикса `noexcept` 👉👈

2023-05-28 13:48 UTC, AngelicHedgehog commented on libs/AnimeDefendersEngine/src/AnimeFramework/Scene.cpp
> +    }
может недальновиден в своём взгляде, но может здесь подойдёт `noexcept`?

2023-05-28 13:57 UTC, AngelicHedgehog approved these changes, later dismissed
окей

2023-05-28 19:01 UTC, Arugaf requested changes

2023-05-28 19:01 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/AnimeFramework/SceneLoader.hpp
> +    };
В отдельный файл.

2023-05-28 19:01 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/AnimeFramework/SceneLoader.hpp
> +    };
Виртуальный деструктор.

2023-05-28 19:01 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/AnimeFramework/SceneManager.hpp
> +        friend class SceneLoader;
nit: осуждаю.

2023-05-28 19:01 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/AnimeFramework/SceneLoader.cpp
> +            std::string line;
`{}`

2023-05-28 20:40 UTC, DPeshkoff requested changes

2023-05-28 20:40 UTC, DPeshkoff commented on libs/AnimeDefendersEngine/src/AnimeFramework/SceneLoader.cpp
> +            std::size_t id = std::stoul(entityParameters[idIndex]);
Давайте проверять `errno` и/или ловить эксепшны, чтобы код был безопасным

2023-05-29 15:13 UTC, Arugaf requested changes

2023-05-29 15:13 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/AnimeFramework/SceneManager.hpp
>          std::unordered_map<int, std::unique_ptr<Scene>> m_scenes;
Что такое `int`?

2023-05-29 15:13 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/AnimeFramework/SceneLoader.cpp
> +            std::size_t id = std::stoul(entityParameters[idIndex]);
Только не `errno`, пожалуйста. Пошто тащишь сюда свои сишные штуки.

2023-05-30 09:41 UTC, Arugaf requested changes

2023-05-30 09:41 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/AnimeFramework/SceneLoader.cpp
> +                continue;
Мб `return`?

2023-05-30 09:48 UTC, BorisKaryshev commented on libs/AnimeDefendersEngine/src/AnimeFramework/SceneLoader.cpp
> +                continue;
Чтобы движок прекращал считывать `Entity` из файла после одного невалидного `sceneId`?

2023-06-01 19:14 UTC, merged