Initial project structure game engine + the game
cpp-park-vk-education/2023_1_Japanese_gardens_and_landscapes pull request #5
Opened 2023-05-14 13:49 UTC by Arugaf

https://park.vk.company/curriculum/program/lesson/23286/#homework_8501

2023-05-14 14:00 UTC, Arugaf reviewed
В целом неплохо. Не считая некоторых очень-очень важных моментов.

Остальное будет непосредственно на ревью отдельных задач.

2023-05-14 14:00 UTC, Arugaf commented on .github/workflows/CI.yml
> +
Лишняя пустая строка.

В целом очень-очень неплохо.

2023-05-14 14:00 UTC, Arugaf commented on CMakeLists.txt
> +    ${PROJECT_SOURCE_DIR}/include/A_lib/A.hpp
Излишне. Мы и так в конкретной директории находимся.

2023-05-14 14:00 UTC, Arugaf commented on CMakeLists.txt
> +    ${PROJECT_SOURCE_DIR}/include/AnimeFramework/AnimeFramework.hpp
Не хочется видеть эти переменные в корневом cmake файле.

2023-05-14 14:00 UTC, Arugaf commented on CMakeLists.txt
> +set(include_locations
Кажется, что такие большие переменные лучше отделять пустой строкой.

2023-05-14 14:00 UTC, Arugaf commented on CMakeLists.txt
> +    ${PROJECT_SOURCE_DIR}/include/A_lib
Что такое A?

2023-05-14 14:00 UTC, Arugaf commented on include/A_lib/A.hpp
> +}  // namespace A
Зачем оставили?

2023-05-14 14:00 UTC, Arugaf commented on include/AnimeFramework/AnimeFramework.hpp
> +namespace AnimeDefendersEngine {
Один единственный неймспейс - неудобно.

2023-05-14 14:00 UTC, Arugaf commented on include/AnimeFramework/AnimeFramework.hpp
> +}  // namespace AnimeDefendersEngine
Во всех файлах потеряли завершающую пустую строку.

2023-05-14 14:00 UTC, Arugaf commented on include/AnimeFramework/GameLoop.hpp
> +        bool is_running = true;
В полях хотелось бы видеть object-like инициализацию вида `bool is_running{true}`.

2023-05-14 14:00 UTC, Arugaf commented on include/Graphics/ITransposeMathWrapper.hpp
> +        virtual auto dropLastMatrix() -> void const = 0;
Нигде нет виртуальных деструкторов... Ну как же так.

2023-05-14 14:00 UTC, Arugaf commented on include/UiColorElementComponent/UiColorElementSystem.hpp
> +        static auto applyUiElementTransform(UiColorElement*) -> void const;
Почему не ссылки?

2023-05-14 14:00 UTC, Arugaf commented on include/UiColorElementComponent/UiColorElement.hpp
> +        std::array<int, 2> m_position;
Магическая константа.

2023-05-14 14:00 UTC, Arugaf commented on include/Math/Graph.hpp
> +        explicit Graph(const std::vector<Component*>& components, int resolution, std::pair<Point, Point> coordinatsRange);
Вместо `std::pair` хочется увидеть кастомную структуру с лучшей семантикой.

2023-05-14 14:00 UTC, Arugaf commented on src/UiColorElementComponent/UiColorElement.cpp
> +auto UiColorElement::setEventOnClick(std::function<void(void*)>) -> void {}
Что за функтор? Не стесняйтесь использовать алиасы.

2023-05-14 16:32 UTC, AngelicHedgehog requested changes
Базовые приколы с форматом кода я исправил, чтобы вас лишний раз не дёргать, но некоторые моменты, которые я указал, стоят внимания, если не сейчас, то потом.

А, и да, **все указатели, использующиеся для компонент или систем заменяем на ссылки**

2023-05-14 16:32 UTC, AngelicHedgehog commented on include/OpenAlDependecy/AudioPlayWrapper.hpp
@MiraiRatchet
Требуется добавить объявление класса

2023-05-14 16:32 UTC, AngelicHedgehog commented on include/Math/Matrix.hpp
> +            explicit Matrix2d(std::size_t rows = 0, std::size_t columns = 0, T val = T{}) {}
@GoshaSerbin 
Нужно добавить пустые реализации методов

2023-05-14 16:32 UTC, AngelicHedgehog commented on include/Math/Vector2.hpp
> +    explicit Vector2(T val1 = T {}, T val2 = T {});
@GoshaSerbin 
Требуется добавить пустые реализации методов

2023-05-14 16:32 UTC, AngelicHedgehog commented on CMakeLists.txt
> +set(include_files
@BorisKaryshev
Нужно(?) вынести в отдельный файл

2023-05-14 16:32 UTC, AngelicHedgehog commented on include/AudioSystem/AudioSystem.hpp
> +        class AudioSystem : public ISystem {};
@MiraiRatchet 
Требуется добавить объявления методов класса и их пустые реализации в src

2023-05-14 16:32 UTC, AngelicHedgehog commented on src/AudioSystem/AudioSystem.cpp
@MiraiRatchet 
Нужно добавить пустые реализации методов аудио-системы

2023-05-14 16:32 UTC, AngelicHedgehog commented on src/OpenALDependecy/AudioPlayWrapper.cpp
@MiraiRatchet 
Нужно пустое наполнение(ну ты поняла)

2023-05-14 16:32 UTC, AngelicHedgehog commented on include/AnimeFramework/MemoryMaster.hpp
> +        auto allocate(size_type size) -> T*;
@BorisKaryshev 
Добавить пустые определения в src

2023-05-15 14:35 UTC, BorisKaryshev commented on include/AnimeFramework/MemoryMaster.hpp
> +        auto allocate(size_type size) -> T*;
Т.к. шаблон, то определения в src быть не должны. 
Добавил непосредственно в хедер.

2023-05-15 14:58 UTC, BorisKaryshev commented on CMakeLists.txt
> +set(include_files
Я пытаюсь вынести движок в отдельную библиотеку чтобы можно было как библиотеку подключить, но там муторно что-то
В любом случае оно не мешает дальше делать наш проект, так что доделаю завтра

2023-05-16 07:07 UTC, BorisKaryshev approved these changes

2023-05-16 16:48 UTC, AngelicHedgehog approved these changes
CI работает, надёжная структура кода сформирована, работаем

2023-05-16 17:09 UTC, merged