Implement base component registration and component manager
cpp-park-vk-education/2023_1_Japanese_gardens_and_landscapes pull request #6
Opened 2023-05-16 10:25 UTC by BorisKaryshev

2023-05-16 19:12 UTC, AngelicHedgehog requested changes
В остальном всё ок

2023-05-16 19:12 UTC, AngelicHedgehog commented on libs/AnimeDefendersEngine/include/AnimeFramework/Component.hpp
> +     private:
Лишнее

2023-05-16 19:12 UTC, AngelicHedgehog commented on libs/AnimeDefendersEngine/include/AnimeFramework/Component.hpp
> +    class Component {
Не хватает отступа от неймспейса

2023-05-16 19:12 UTC, AngelicHedgehog commented on libs/AnimeDefendersEngine/src/AnimeFramework/ComponentManager.cpp
> +}
Не хватает пустой строки в eof

2023-05-16 19:15 UTC, AngelicHedgehog commented on libs/AnimeDefendersEngine/include/AnimeFramework/ComponentManager.hpp
> +    class Component;
Здесь, кстати, тоже перенос строки не помешает

2023-05-16 19:16 UTC, AngelicHedgehog commented
Так же переименуйте, пожалуйста, название пр в соответстии с номером таска

2023-05-17 15:02 UTC, AngelicHedgehog submitted a review, later dismissed
Всё норм на мой взгляд, одобряю

2023-05-18 00:05 UTC, Arugaf requested changes

2023-05-18 00:05 UTC, Arugaf commented on libs/AnimeDefendersEngine/CMakeLists.txt
> +endif()
#8

2023-05-18 00:05 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/AnimeFramework/AnimeFramework.hpp
>          GameLoop m_gameloop;
В чем конкретно назначение класса? Нужна документация.

2023-05-18 00:05 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/AnimeFramework/AnimeFramework.hpp
> +        std::shared_ptr<IComponentManager> m_globalComponentsManager;
По инклюдам: предпочитаем использование forward declaration.

2023-05-18 00:05 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/AnimeFramework/Component.hpp
> +#include "ComponentManager.hpp"
Forward declaration.

2023-05-18 00:05 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/AnimeFramework/Component.hpp
> +        }
Какой смысл в определении конструктора в теле класса?

2023-05-18 00:05 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/AnimeFramework/Component.hpp
> +            m_compManager.lock()->addComponent(m_typeId, this);
Нарушается принцип наименьшего удивления.

2023-05-18 00:05 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/AnimeFramework/Component.hpp
> +            if (!m_compManager.expired()) {
Есть ли такие случаи, когда `ComponentManager` может умереть раньше компонента? Звучит странно.

2023-05-18 00:05 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/AnimeFramework/Component.hpp
> +        std::weak_ptr<IComponentManager> m_compManager;
Предлагаю использовать ссылку вместо `std::weak_ptr`.

2023-05-18 00:05 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/AnimeFramework/ComponentManager.hpp
> +    class Component;
Предлагаю выносить forward declaration отдельно, не впихивая его в то же место, где и объявление класса.

Т.е. еще раз продублировать имя неймспейса, чтобы явно отделить предварительное объявление.

2023-05-18 00:05 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/AnimeFramework/ComponentManager.hpp
>      class IComponentManager {
Мб и на сам класс добавить документацию?

2023-05-18 00:05 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/AnimeFramework/ComponentManager.hpp
> +        virtual void deleteComponent(std::type_index typeId, Component* compoment) = 0;
Атрибуты, спецификаторы.

2023-05-18 00:05 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/AnimeFramework/ComponentManager.hpp
> +        virtual auto getComponents(std::type_index typeId) -> std::vector<Component*> = 0;
Либо везде trailing return type, либо нигде.

2023-05-18 00:05 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/AnimeFramework/ComponentManager.hpp
> +        virtual auto getComponents(std::type_index typeId) -> std::vector<Component*> = 0;
`const`

2023-05-18 00:05 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/AnimeFramework/ComponentManager.hpp
> +
Доку обычно приклеивают к описываемой части.

2023-05-18 00:05 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/AnimeFramework/ComponentManager.hpp
> +            return this->getComponents(typeid(T)) | std::views::filter(helper);
Вообще я бы все же старался не полагаться на typeid. Могут возникнуть проблемы с сериализацией данных и их переносимостью (надо более подробно изучать кейс).

2023-05-18 00:05 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/AnimeFramework/ComponentManager.hpp
> +            return this->getComponents(typeid(T)) | std::views::filter(helper);
Лучше в доку добавить более подробное описание работы данного класса.

2023-05-18 00:05 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/AnimeFramework/ComponentManager.hpp
> +        std::unordered_map<std::type_index, std::vector<Component*>> m_components;
Может лучше все же разделять владение компонентом?

2023-05-18 00:05 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/AnimeFramework/ComponentManager.cpp
>  using namespace AnimeDefendersEngine;
Плохой `using`. Корректнее обернуть определения методов. Даже clang-tidy ругается.

2023-05-18 00:05 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/AnimeFramework/ComponentManager.cpp
> +    m_components[typeId].emplace_back(component);
Нет необходимости в `emplace_back`. Можно просто `push_back`.

2023-05-18 00:05 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/AnimeFramework/ComponentManager.cpp
> +    return m_components[typeId];
Потенциальный вызов дефолтного конструктора - ожидаемое поведение?

2023-05-18 00:05 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/AnimeFramework/Entity.cpp
>      return nullptr;
Заглушка?

2023-05-18 00:05 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/AnimeFramework/Entity.cpp
> +auto Entity::getComponent(std::type_index) -> Component* {
Если так хочется играть на типах, то вместо RTTI было бы логичнее и нагляднее использовать шаблоны, как мне кажется. Но, думаю, уже не стоит ворошить архитектуру.

2023-05-18 00:05 UTC, Arugaf commented on tests/AnimeFramework.cpp
> +    ASSERT_TRUE(true);
Ладно.

2023-05-20 17:24 UTC, Arugaf requested changes

2023-05-20 17:24 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/AnimeFramework/Component.hpp
> +        [[nodiscard]] auto getEntityId() const noexcept -> std::string;
`const std::string&`

2023-05-20 17:24 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/AnimeFramework/ComponentManager.hpp
> +            return components[this];
Выглядит как слегка грязный хак.

2023-05-20 17:24 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/AnimeFramework/ComponentManager.hpp
> +            if (components.contains(component->getEntityId()) && components[component->getEntityId()] == component) {
Два раза стучимся. Можно заменить на один find.

2023-05-20 18:05 UTC, AngelicHedgehog requested changes
Ок

2023-05-20 18:05 UTC, AngelicHedgehog commented on libs/AnimeDefendersEngine/include/AnimeFramework/BaseComponent.hpp
> +        }
Реализации в хедере

2023-05-20 18:05 UTC, AngelicHedgehog commented on libs/AnimeDefendersEngine/include/AnimeFramework/BaseComponent.hpp
> +        BaseComponent(const BaseComponent& component) : BaseComponent{component.getEntityId(), component.m_compManager} {}
explicit

2023-05-20 18:05 UTC, AngelicHedgehog commented on libs/AnimeDefendersEngine/include/AnimeFramework/BaseComponent.hpp
> +namespace AnimeDefendersEngine {
Два одинаковых нейспейса?
Я, конечно, помню были разговоры какие-то про эту тему, но, насколько я помню, речь шла про разного уровня именные пространства

2023-05-22 15:04 UTC, AngelicHedgehog submitted a review, later dismissed
вопросов нет

2023-05-23 11:01 UTC, AngelicHedgehog approved these changes
ok

2023-05-23 13:42 UTC, Arugaf approved these changes
LGTM

2023-05-23 13:50 UTC, merged