[ADEF-BBS-011] Graphics: Renderer: base implementation with Sprite-component support
cpp-park-vk-education/2023_1_Japanese_gardens_and_landscapes pull request #8
Opened 2023-05-16 17:31 UTC by AngelicHedgehog

[Ссылка на таск](https://flat-bottle-4d0.notion.site/e3d2ba35195643b291d7250ce87daa78?v=737c366dd1154bdd842f008a7eadae01&p=f2d3e321dd104593acce2c29a2b36f89&pm=c)

Необходимо реализовать конструктор для класса Renderer, который будет создавать новое окно через интерфейс IWindow, и метод renderObjects, который будет получать из переданной ему сцены ComponentManager, а уже из него будет получать вектора указателей на компоненты, которые нужно отрисовать (в рамках данной задачи лишь Sprite), после чего будет вызван метод updateFrame интерфейса IWindow

2023-05-18 18:58 UTC, Arugaf requested changes

2023-05-18 18:58 UTC, Arugaf commented on libs/AnimeDefendersEngine/CMakeLists.txt
> +endif()
#6

2023-05-18 18:58 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/AnimeFramework/AnimeFramework.hpp
> +        std::shared_ptr<IComponentManager> m_globalComponentsManager;
Есть другие виды `componentManager`?

2023-05-18 18:58 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/AnimeFramework/Component.hpp
> +    class Component {
Это же базовый класс?

2023-05-18 18:58 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/AnimeFramework/Component.hpp
> +        }
Не надо повсюду делать реализацию в теле класса.

2023-05-18 18:58 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/AnimeFramework/Entity.hpp
> +        auto getComponent(std::type_index componentType) -> Component*;
`const`

2023-05-18 18:58 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/Graphics/Renderer.cpp
> +        assert(nextCamera = dynamic_cast<Camera*>(nextCompenent));
Плохо читаемый код.

2023-05-18 18:58 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/Graphics/Renderer.cpp
> +        assert(nextCamera = dynamic_cast<Camera*>(nextCompenent));
Есть ли смысл в ассерте? Можно просто продолжить цикл?

2023-05-18 18:58 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/Graphics/Renderer.cpp
> +    Camera* nextCamera{};
Нет смысла предварительно объявлять те переменные, которые будут на стеке и не подразумевает множественный вызов одного и того же (например метод `size()` у `std::vector`).

2023-05-18 18:58 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/Graphics/Renderer.cpp
> +        }
Плохо передаваемое управление.

2023-05-18 18:58 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/Graphics/Renderer.cpp
> +    }
[std::find_first_of](https://en.cppreference.com/w/cpp/algorithm/find_first_of)

2023-05-18 18:58 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/Graphics/Renderer.cpp
> +    }
[std::ranges::find_first_of](https://en.cppreference.com/w/cpp/algorithm/ranges/find_first_of)

2023-05-18 18:58 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/Graphics/Renderer.cpp
> +    activeCamera->applyCameraView();
Для соответствующих методов нужны пояснение и документация.

2023-05-18 18:58 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/Graphics/Renderer.cpp
> +        if (!nextSprite->isSpriteVisibleToCamera(activeCamera)) {
Кажется, что логичнее делать наоборот. Чтобы камера знала о том, что у нее есть.

2023-05-18 18:58 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/Graphics/Renderer.cpp
> +    }
Через рейнджи отфильтровать?

2023-05-18 18:58 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/Graphics/Renderer.cpp
> +        assert(nextUiElement = dynamic_cast<UiElement*>(nextComponent));
Не нравится мне вся эта затея с бойлерплейтными `dynamic_cast`.

Насколько точно вообще обеспечивается гарантия корректного даункаста?

Если гарантия не полная, то assert не будет стрелять в релизной версии, а значит нужно полагаться на какой-то метод обработки ошибок. Бтв, надо бы вообще чекнуть, не будет ли все выражение под ним выкинуто в релизной версии. Именно из-за этого не стоит под ассерт кидать какую-то логику.

2023-05-18 18:58 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/SpriteComponent/Sprite.cpp
> +auto Sprite::isSpriteVisibleToCamera(const Camera*) -> bool {
Советую все же использовать ссылки.

Разве тут возможна такая ситуация, когда мы подадим невалидный указатель на камеру?

2023-05-28 20:48 UTC, Arugaf requested changes

2023-05-28 20:48 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/Graphics/Renderer.cpp
> +                    throw std::runtime_error("Active camera must be the only one!");
Поправить на норм английский.

2023-05-28 20:48 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/Graphics/Renderer.cpp
> +        for (const auto& nextCompenent : cameras) {
Просто `component`.

2023-05-28 20:48 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/Graphics/Renderer.cpp
> +        auto uiElements = componentManager.getComponents<UiElement>();
Возвращает ссылки или нет?

2023-05-28 21:17 UTC, DPeshkoff submitted a review, later dismissed

2023-05-28 21:17 UTC, DPeshkoff commented on libs/AnimeDefendersEngine/src/Graphics/Renderer.cpp
> +        Camera* activeCamera{};
А почему голый указатель?

2023-05-28 21:25 UTC, AngelicHedgehog commented on libs/AnimeDefendersEngine/src/Graphics/Renderer.cpp
> +        Camera* activeCamera{};
Потому что такова семантика работы ComponentManager

2023-05-29 12:33 UTC, Arugaf approved these changes

2023-05-29 13:04 UTC, BorisKaryshev approved these changes
В целом, норм

2023-05-29 13:04 UTC, BorisKaryshev commented on libs/AnimeDefendersEngine/src/Graphics/Renderer.cpp
> +        std::ranges::views::transform([](const auto& sprite) { return sprite->drawSprite(); });
Вызывается модифицирующий метод у константой ссылки

2023-05-29 13:04 UTC, BorisKaryshev commented on libs/AnimeDefendersEngine/src/Graphics/Renderer.cpp
> +    std::as_const(uiElements) | std::ranges::views::transform([](const auto& uiElement) { return uiElement->drawUiElement(); });
Аналогично

2023-05-29 13:04 UTC, BorisKaryshev commented on libs/AnimeDefendersEngine/src/Graphics/Renderer.cpp
> +    assert(activeCameras.size() == 1);
Точно ли правильно останавливать программу при такой ошибке?

2023-05-29 13:04 UTC, BorisKaryshev commented on libs/AnimeDefendersEngine/include/Graphics/Renderer.hpp
> +        auto getActiveWindowPtr() const noexcept -> std::shared_ptr<IWindow>;
nit: `[[nodiscard]]`

2023-05-29 13:04 UTC, BorisKaryshev commented on libs/AnimeDefendersEngine/src/Graphics/Renderer.cpp
> +        for (const auto& compenent : cameras) {
nit: structured binding?
`const auto& [entityId, component] : cameras`

Так будет сильно читаемей, чем `component.second`

2023-05-29 13:04 UTC, BorisKaryshev commented on libs/AnimeDefendersEngine/src/Graphics/Renderer.cpp
> +                    throw std::runtime_error("The active camera should be the only one! At the moment there are more.");
nit: мб в логгер писать и как-то обрабатывать ошибку тут, а не завершать программу? Или она обрабатывается выше?

2023-05-29 13:04 UTC, BorisKaryshev commented on libs/AnimeDefendersEngine/src/Graphics/Renderer.cpp
> +            throw std::runtime_error("The active camera should be the only one! At the moment they are not.");
nit: Аналогично

2023-05-29 13:04 UTC, BorisKaryshev commented on libs/AnimeDefendersEngine/src/Graphics/Renderer.cpp
> +        for (const auto& component : sprites) {
nit: structured binding

2023-05-29 13:04 UTC, BorisKaryshev commented on libs/AnimeDefendersEngine/src/Graphics/Renderer.cpp
> +        for (const auto& component : uiElements) {
nit: structured binding

2023-05-29 14:25 UTC, merged