[ADEF-BBS-005] Physics: Collision: impelementation of collision handler detection
cpp-park-vk-education/2023_1_Japanese_gardens_and_landscapes pull request #9
Opened 2023-05-17 08:18 UTC by GoshaSerbin

[Ссылка на таск](https://www.notion.so/CollisionHandler-2d85b9cb842643fa86fe3f5aa0341d0b?pvs=4)

Реализовать метод класса CollisionHandler, который сможет проверять коллизии двух объектов. Так же нужно написать методы narrow phase и broad phase

2023-05-17 16:11 UTC, AngelicHedgehog requested changes
В остальном проблем не обнаружил

2023-05-17 16:11 UTC, AngelicHedgehog commented on libs/AnimeDefendersEngine/include/Physics/Body.hpp
> +            virtual auto getShapeType() const -> ShapeType;
Нужно разделить на смысловые группы для читабельности

2023-05-17 16:11 UTC, AngelicHedgehog commented on libs/AnimeDefendersEngine/include/Physics/BodyDefinition.hpp
>  }  // namespace AnimeDefendersEngine
Не хватает пустой строки в eof

2023-05-17 16:11 UTC, AngelicHedgehog commented on libs/AnimeDefendersEngine/include/Physics/Manifold.hpp
>          struct Manifold {
Нужен отступ от объявления неймспейса

2023-05-17 16:11 UTC, AngelicHedgehog commented on libs/AnimeDefendersEngine/include/Physics/Manifold.hpp
>      }  // namespace Physics
Здесь тоже отступ

2023-05-17 16:11 UTC, AngelicHedgehog commented on libs/AnimeDefendersEngine/src/Physics/Body.cpp
> +};
Точка с запятой после объявления тела функции лишние
Аналогично на 47 строке

2023-05-17 16:11 UTC, AngelicHedgehog commented on libs/AnimeDefendersEngine/src/Physics/CollisionHandler.cpp
> +    contact.penetration = 0;  // it was done for working CI
Почему не реализовано в рамках данного таска?

2023-05-17 16:11 UTC, AngelicHedgehog commented on libs/AnimeDefendersEngine/src/Physics/CollisionHandler.cpp
> +    closestVertexToCircleCenter.y = std::max(closestVertexToCircleCenter.y, -y_extent);
Слишком визуально нагруженный блок, раздели пустыми строками

2023-05-17 16:36 UTC, GoshaSerbin commented on libs/AnimeDefendersEngine/src/Physics/CollisionHandler.cpp
> +    contact.penetration = 0;  // it was done for working CI
В рамках данной таски реализовано определение факта наличия коллизии (есть или нет). Уточнение коллизии (нахождение вектора нормали и глубины внедрения) и разрешение коллизий в других тасках

2023-05-17 17:39 UTC, AngelicHedgehog reviewed
Не все замечания рассмотрены

2023-05-17 18:02 UTC, AngelicHedgehog requested changes
Вне очереди пару правок

2023-05-17 18:02 UTC, AngelicHedgehog commented on libs/AnimeDefendersEngine/src/Physics/BodyDefinition.cpp
> +BodyDefinition::BodyDefinition() : id(), shapeUPtr(nullptr), bodyType(), transform(), velocity(), layers(), force(), isTrigger() {}
Подобные дефолтные конструкторы нужно оставлять на уровне объявления класса:
Вместо `<...> : id(), <...>` нужно `int id{};`

2023-05-17 18:02 UTC, AngelicHedgehog commented on libs/AnimeDefendersEngine/include/Physics/PhysicsWorld.hpp
>              float m_fixedDeltaTime;
Нет дефолтного конструктора для float (а нужен)

2023-05-17 18:02 UTC, AngelicHedgehog commented on libs/AnimeDefendersEngine/include/Physics/Manifold.hpp
>              float penetration;
Дефолтный конструктор нужен

2023-05-17 18:02 UTC, AngelicHedgehog commented on libs/AnimeDefendersEngine/include/Physics/BodyDefinition.hpp
> +            BodyDefinition(BodyDefinition&& other);
Нарушено правило 0-3-5

2023-05-17 19:10 UTC, AngelicHedgehog submitted a review, later dismissed
Теперь ок

2023-05-17 19:10 UTC, AngelicHedgehog commented on libs/AnimeDefendersEngine/include/Physics/Manifold.hpp
> +            Body* bodyB{nullptr};
Здесь достаточно было дефолтного конструктора, суть та же

2023-05-18 19:32 UTC, Arugaf requested changes
Форматирование привести в порядок.

2023-05-18 19:32 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/Physics/Body.hpp
>      namespace Physics {
`namespace AnimeDefendersEngine::Physics`

2023-05-18 19:32 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/Physics/Body.hpp
>              Body(BodyDefinition&& bodyDefinition);
`explicit`

2023-05-18 19:32 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/Physics/Body.hpp
> +            virtual auto applyForce(Math::Vector2<float> vec) -> void;
Неймспейс `Math` - это внутренний неймспейс? Если да, то предлагаю завести общий (в хедере) алиас `Math::Vector2f`

2023-05-18 19:32 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/Physics/BodyDefinition.hpp
> +            Transform(Math::Vector2<float> position = Math::Vector2<float>()) : position(position){};
Конструкторы в начало.

2023-05-18 19:32 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/Physics/BodyDefinition.hpp
> +            ~BodyDefinition(){};
Слишком намешано и плохо читается.

2023-05-18 19:32 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/Physics/BodyDefinition.hpp
> +            std::unique_ptr<Shape> shapeUPtr{nullptr};
У `std::unique_ptr` есть дефолтный конструктор. `nullptr` и вообще `{}` можно не указывать.

2023-05-18 19:32 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/Physics/BodyDefinition.hpp
> +            std::unique_ptr<Shape> shapeUPtr{nullptr};
UPtr часть не нужна. Лучше стараться вообще не указывать типы в названиях переменных.

2023-05-18 19:32 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/Physics/BodyDefinition.hpp
> +            BodyType bodyType{};
Аналогично: дефолтный конструктор. И для всех нетривиальных типов так.

2023-05-18 19:32 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/Physics/BodyDefinition.hpp
> +            bool isTrigger{};
Для тривиальных типов лучше явно указывать что за дефолтное значение.

2023-05-18 19:32 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/Physics/BodyDefinition.hpp
> +            BodyDefinition(){};
`= default`

2023-05-18 19:32 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/Physics/BodyDefinition.hpp
> +            ~BodyDefinition(){};
`= default`

2023-05-18 19:32 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/Physics/PhysicsWorld.hpp
> +            auto removeBody(Body* body) -> void;
`const` аргумент?

2023-05-18 19:32 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/Physics/Shape.hpp
>          };
Непонятно зачем этому `enum` какие-то конкретные численные значения.

2023-05-18 19:32 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/Physics/Shape.hpp
> +        enum ShapeType {
Не используем чистый `enum` в любом случае.

`enum class name : int ` при необходимости.

2023-05-18 19:32 UTC, Arugaf commented on libs/AnimeDefendersEngine/include/Physics/Shape.hpp
>              static constexpr int shapeCount = 2;
Для чего? Для кого?

2023-05-18 19:32 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/Physics/CollisionHandler.cpp
> +}
Все налепил.

2023-05-18 19:32 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/Physics/CollisionHandler.cpp
> +    return normal.norm() < circleB->radius;
А здесь разлепил.

2023-05-18 19:32 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/Physics/CollisionHandler.cpp
>  using namespace AnimeDefendersEngine::Physics;
Плохо.

2023-05-18 19:32 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/Physics/CollisionHandler.cpp
> +        for (size_t j = i + 1; j < bodies.size(); ++j) {
Не вижу тут ни одной причины не использовать range-based for loop.

2023-05-18 19:32 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/Physics/CollisionHandler.cpp
> +            contacts.push_back(contact);
`contacts.emplace_back(bodyA, bodyB);`

2023-05-18 19:32 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/Physics/CollisionHandler.cpp
> +    std::vector<Manifold> contacts(bodies.size());
Явный вызов дефолтного конструктора.

2023-05-18 19:32 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/Physics/CollisionHandler.cpp
> +            resolveCollision(*contactIterator);
Непонятна последовательность. На весь класс хочется документацию.

2023-05-18 19:32 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/Physics/CollisionHandler.cpp
> +            contactIterator++;
Префикс.

2023-05-18 19:32 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/Physics/CollisionHandler.cpp
> +    Circle* circleB = dynamic_cast<Circle*>(bodyB->getShape());
Точно ли есть гарантии? Если да, то ок.

2023-05-18 19:32 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/Physics/CollisionHandler.cpp
> +    float distance = (bodyA->getPosition() - bodyB->getPosition()).norm();
`auto` (`auto&`, `const auto`, `const auto&`, лучше константные всегда).

2023-05-18 19:32 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/Physics/CollisionHandler.cpp
> +}
Вместо приватности на единицу трансляции через static, нужно использовать анонимный неймспейс.

2023-05-18 19:32 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/Physics/CollisionHandler.cpp
>      return false;
Упростить в

```cpp
if (xOverlap > 0) {
   const auto yOverlap = (rectangleA->size.y + rectangleB->size.y) / 2 - std::abs(normal.y);
   return yOverlap > 0;
}
return false;
```

2023-05-18 19:32 UTC, Arugaf commented on libs/AnimeDefendersEngine/src/Physics/CollisionHandler.cpp
> +};
Оооооочень плохо читаемо. Слишком сложно. Даже не очень понятно, что это в принципе плюсы.

2023-05-18 19:32 UTC, Arugaf requested changes
Форматирование привести в порядок.

2023-05-18 21:21 UTC, GoshaSerbin commented on libs/AnimeDefendersEngine/src/Physics/CollisionHandler.cpp
> +    Circle* circleB = dynamic_cast<Circle*>(bodyB->getShape());
Да

2023-05-18 21:26 UTC, GoshaSerbin commented on libs/AnimeDefendersEngine/include/Physics/PhysicsWorld.hpp
> +            auto removeBody(Body* body) -> void;
Давай я это поправлю когда буду выполнять таск с реализацией класса PhysicsWorld

2023-05-18 21:50 UTC, GoshaSerbin commented on libs/AnimeDefendersEngine/include/Physics/Shape.hpp
>              static constexpr int shapeCount = 2;
Думал правильно так писать

2023-05-22 13:18 UTC, merged